import { Account, Customer, Supplier, InventoryItem, JournalEntry, Invoice, CompanyProfile, SystemUser, UnitDefinition } from '../types.js';

export const INITIAL_USERS: SystemUser[] = [
  {
    id: 'user-001',
    name: 'د. خالد السليمان',
    username: 'admin',
    email: 'admin@logixerp.com',
    role: 'ADMIN',
    roleTitleAr: 'المدير العام والتنفيذي',
    isActive: true,
    pinCode: '1234',
  },
  {
    id: 'user-002',
    name: 'أ. محمد الشمري',
    username: 'chief_acc',
    email: 'chief_acc@logixerp.com',
    role: 'CHIEF_ACCOUNTANT',
    roleTitleAr: 'المدير المالي والمحاسب الرئيسي',
    isActive: true,
    pinCode: '2233',
  },
  {
    id: 'user-003',
    name: 'أ. أحمد المصطفى',
    username: 'accountant',
    email: 'accountant@logixerp.com',
    role: 'ACCOUNTANT',
    roleTitleAr: 'محاسب عام ومسؤول الفواتير',
    isActive: true,
    pinCode: '1122',
  },
  {
    id: 'user-004',
    name: 'سارة العتيبي',
    username: 'sales',
    email: 'sales@logixerp.com',
    role: 'SALES',
    roleTitleAr: 'مسؤولة المبيعات والعملاء',
    isActive: true,
    pinCode: '4455',
  },
  {
    id: 'user-005',
    name: 'م. فهد الدوسري',
    username: 'auditor',
    email: 'auditor@logixerp.com',
    role: 'AUDITOR',
    roleTitleAr: 'مدقق حسابات ومراجع خارجي',
    isActive: true,
    pinCode: '9900',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  // 1000 - Assets (الأصول)
  {
    id: 'acc-1000',
    code: '1000',
    nameAr: 'الأصول',
    nameEn: 'Assets',
    category: 'ASSET',
    parentId: null,
    level: 1,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
    description: 'إجمالي أصول المنشأة',
  },
  {
    id: 'acc-1100',
    code: '1100',
    nameAr: 'الأصول المتداولة',
    nameEn: 'Current Assets',
    category: 'ASSET',
    parentId: 'acc-1000',
    level: 2,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1110',
    code: '1110',
    nameAr: 'النقدية وما في حكمها',
    nameEn: 'Cash & Cash Equivalents',
    category: 'ASSET',
    parentId: 'acc-1100',
    level: 3,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1111',
    code: '1111',
    nameAr: 'بنك الكويت الوطني (NBK) - الحساب الرئيسي',
    nameEn: 'National Bank of Kuwait (NBK)',
    category: 'ASSET',
    parentId: 'acc-1110',
    level: 4,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1112',
    code: '1112',
    nameAr: 'بيت التمويل الكويتي (KFH) - حساب العمليات',
    nameEn: 'Kuwait Finance House (KFH)',
    category: 'ASSET',
    parentId: 'acc-1110',
    level: 4,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1113',
    code: '1113',
    nameAr: 'الصندوق الرئيسي (الخزينة)',
    nameEn: 'Main Cash Box',
    category: 'ASSET',
    parentId: 'acc-1110',
    level: 4,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1120',
    code: '1120',
    nameAr: 'الذمم المدينة (حسابات العملاء والجمعيات التعاونية)',
    nameEn: 'Accounts Receivable (Coops)',
    category: 'ASSET',
    parentId: 'acc-1100',
    level: 3,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1130',
    code: '1130',
    nameAr: 'مخزون البضائع والبهارات والمنتجات',
    nameEn: 'Merchandise Inventory',
    category: 'ASSET',
    parentId: 'acc-1100',
    level: 3,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },

  // 1200 - Fixed Assets
  {
    id: 'acc-1200',
    code: '1200',
    nameAr: 'الأصول غير المتداولة (الثابتة)',
    nameEn: 'Non-Current Assets',
    category: 'ASSET',
    parentId: 'acc-1000',
    level: 2,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1210',
    code: '1210',
    nameAr: 'المعدات وآلات التعبئة والتغليف',
    nameEn: 'Packaging & Production Equipment',
    category: 'ASSET',
    parentId: 'acc-1200',
    level: 3,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-1220',
    code: '1220',
    nameAr: 'وسائل النقل والسيارات',
    nameEn: 'Vehicles & Delivery Vans',
    category: 'ASSET',
    parentId: 'acc-1200',
    level: 3,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },

  // 2000 - Liabilities (الخصوم)
  {
    id: 'acc-2000',
    code: '2000',
    nameAr: 'الخصوم والالتزامات',
    nameEn: 'Liabilities',
    category: 'LIABILITY',
    parentId: null,
    level: 1,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-2100',
    code: '2100',
    nameAr: 'الخصوم المتداولة',
    nameEn: 'Current Liabilities',
    category: 'LIABILITY',
    parentId: 'acc-2000',
    level: 2,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-2110',
    code: '2110',
    nameAr: 'الذمم الدائنة (حسابات الموردين)',
    nameEn: 'Accounts Payable',
    category: 'LIABILITY',
    parentId: 'acc-2100',
    level: 3,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },

  // 3000 - Equity (حقوق الملكية)
  {
    id: 'acc-3000',
    code: '3000',
    nameAr: 'حقوق الملكية',
    nameEn: 'Equity',
    category: 'EQUITY',
    parentId: null,
    level: 1,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-3100',
    code: '3100',
    nameAr: 'رأس المال المكتتب به / الأرصدة الافتتاحية',
    nameEn: 'Capital & Opening Balances',
    category: 'EQUITY',
    parentId: 'acc-3000',
    level: 2,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-3200',
    code: '3200',
    nameAr: 'الأرباح المبقاة (المدورة)',
    nameEn: 'Retained Earnings',
    category: 'EQUITY',
    parentId: 'acc-3000',
    level: 2,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },

  // 4000 - Revenue (الإيرادات)
  {
    id: 'acc-4000',
    code: '4000',
    nameAr: 'الإيرادات والمبيعات',
    nameEn: 'Revenue',
    category: 'REVENUE',
    parentId: null,
    level: 1,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-4100',
    code: '4100',
    nameAr: 'إيرادات مبيعات الجمعيات والبهارات',
    nameEn: 'Sales Revenue',
    category: 'REVENUE',
    parentId: 'acc-4000',
    level: 2,
    normalBalance: 'CREDIT',
    isSystem: true,
    isActive: true,
  },

  // 5000 - Expenses (المصروفات)
  {
    id: 'acc-5000',
    code: '5000',
    nameAr: 'المصروفات',
    nameEn: 'Expenses',
    category: 'EXPENSE',
    parentId: null,
    level: 1,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-5100',
    code: '5100',
    nameAr: 'تكلفة البضاعة المباعة (COGS)',
    nameEn: 'Cost of Goods Sold',
    category: 'EXPENSE',
    parentId: 'acc-5000',
    level: 2,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-5200',
    code: '5200',
    nameAr: 'المصروفات العمومية والإدارية والتسويقية',
    nameEn: 'General & Admin Expenses',
    category: 'EXPENSE',
    parentId: 'acc-5000',
    level: 2,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
  {
    id: 'acc-5210',
    code: '5210',
    nameAr: 'مصروف الرواتب والأجور',
    nameEn: 'Salaries Expense',
    category: 'EXPENSE',
    parentId: 'acc-5200',
    level: 3,
    normalBalance: 'DEBIT',
    isSystem: true,
    isActive: true,
  },
];

// All Customers (جمعيات تعاونية وشركات مهيأة بأرصدة صفرية نظيفة لبدء العمليات)
export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-alwaleed',
    code: 'CUST-001',
    nameAr: 'مطحنة الوليد المتحدة (عميل تجاري)',
    nameEn: 'Al-Waleed United Mill (Commercial Client)',
    phone: '+965 2244 8899',
    address: 'شارع السور - القبلة',
    governorate: 'العاصمة',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '2026-01-01',
    isActive: true,
  },
  {
    id: 'cust-9407',
    code: '9407',
    nameAr: 'شركة الجليب للتجارة والاستثمار',
    nameEn: 'Jleeb Trading & Investment Co.',
    phone: '+965 2431 8000',
    address: 'العاصمة - المجمع الرئيسي',
    governorate: 'العاصمة',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-4568',
    code: '4568',
    nameAr: 'جمعية القيروان التعاونية',
    nameEn: 'Qairawan Co-op Society',
    phone: '+965 2467 9000',
    address: 'القيروان',
    governorate: 'القيروان',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-3124',
    code: '3124',
    nameAr: 'جمعية الصباحية التعاونية',
    nameEn: 'Sabahiya Co-op Society',
    phone: '+965 2361 5000',
    address: 'الصباحية',
    governorate: 'الصباحية',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-0875',
    code: '875',
    nameAr: 'جمعية الاحمدي التعاونية',
    nameEn: 'Ahmadi Co-op Society',
    phone: '+965 2398 2000',
    address: 'الاحمدي',
    governorate: 'الاحمدي',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-3900',
    code: '3900',
    nameAr: 'جمعية صباح الأحمد التعاونية',
    nameEn: 'Sabah Al-Ahmad Co-op Society',
    phone: '+965 2320 1000',
    address: 'صباح الأحمد',
    governorate: 'صباح الأحمد',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-0301',
    code: '301',
    nameAr: 'جمعية شمال غرب الصليبيخات التعاونية',
    nameEn: 'NW Sulaibikhat Co-op Society',
    phone: '+965 2461 4000',
    address: 'شمال غرب',
    governorate: 'شمال غرب',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-5563',
    code: '5563',
    nameAr: 'جمعية بيان التعاونية',
    nameEn: 'Bayan Co-op Society',
    phone: '+965 2538 3000',
    address: 'بيان',
    governorate: 'بيان',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-2035',
    code: '2035',
    nameAr: 'جمعية مدينة سعد العبدالله التعاونية',
    nameEn: 'Saad Al-Abdullah City Co-op Society',
    phone: '+965 2453 6000',
    address: 'سعد',
    governorate: 'سعد',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-3764',
    code: '3764',
    nameAr: 'جمعية سلوى التعاونية',
    nameEn: 'Salwa Co-op Society',
    phone: '+965 2562 7000',
    address: 'سلوى',
    governorate: 'سلوى',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-2537',
    code: '2537',
    nameAr: 'جمعية علي صباح السالم التعاونية',
    nameEn: 'Ali Sabah Al-Salem Co-op Society',
    phone: '+965 2328 8000',
    address: 'علي صباح السالم',
    governorate: 'علي صباح السالم',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-7575',
    code: '7575',
    nameAr: 'جمعية صباح الناصر التعاونية',
    nameEn: 'Sabah Al-Nasser Co-op Society',
    phone: '+965 2488 1000',
    address: 'صباح الناصر',
    governorate: 'صباح الناصر',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-4640',
    code: '4640',
    nameAr: 'جمعية مبارك الكبير التعاونية',
    nameEn: 'Mubarak Al-Kabeer Co-op Society',
    phone: '+965 2542 0000',
    address: 'مبارك الكبير',
    governorate: 'مبارك الكبير',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'cust-1804',
    code: '1804',
    nameAr: 'جمعية اشبيلية التعاونية',
    nameEn: 'Ishbiliya Co-op Society',
    phone: '+965 2434 5000',
    address: 'اشبيلية',
    governorate: 'اشبيلية',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'supp-001',
    code: 'SUPP-201',
    nameAr: 'شركة مطاحن الدقيق والمطاحن الكويتية',
    nameEn: 'Kuwait Flour Mills & Bakeries Co.',
    taxNumber: '1109823',
    phone: '+965 2484 1888',
    email: 'info@kfmb.com.kw',
    address: 'الشويخ الصناعية - الكويت',
    governorate: 'العاصمة',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
  {
    id: 'supp-002',
    code: 'SUPP-202',
    nameAr: 'شركة التوريدات والبهارات العالمية',
    nameEn: 'Global Spices & Foodstuffs Co.',
    taxNumber: '228810',
    phone: '+965 2241 5500',
    email: 'orders@globalspices.kw',
    address: 'الري - المنطقة الصناعية',
    governorate: 'الفروانية',
    city: 'الكويت',
    balance: 0,
    openingBalance: 0,
    openingBalanceDate: '',
  },
];

// All Items transcribed from the attached Image 1
export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-101',
    sku: '2881016018603',
    barcode: '2881016018603',
    nameAr: 'فلفل اسود حب 80 جم',
    nameEn: 'Black Pepper Whole 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.240,
    salePrice: 0.400,
    quantityOnHand: 450,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-102',
    sku: '2881016018610',
    barcode: '2881016018610',
    nameAr: 'فلفل اسود ناعم 80 جم',
    nameEn: 'Black Pepper Powder 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.240,
    salePrice: 0.400,
    quantityOnHand: 380,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-103',
    sku: '2881016018672',
    barcode: '2881016018672',
    nameAr: 'قرنفل مسمار 70 جم',
    nameEn: 'Cloves Whole 70g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.231,
    salePrice: 0.500,
    quantityOnHand: 290,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-104',
    sku: '2881016019044',
    barcode: '2881016019044',
    nameAr: 'دارسين عود 150 جم',
    nameEn: 'Cinnamon Sticks 150g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.225,
    salePrice: 0.400,
    quantityOnHand: 310,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-105',
    sku: '2881016018696',
    barcode: '2881016018696',
    nameAr: 'كزبره حب 60 جم',
    nameEn: 'Coriander Seeds 60g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.048,
    salePrice: 0.200,
    quantityOnHand: 520,
    minQuantityAlert: 60,
    isActive: true,
  },
  {
    id: 'inv-106',
    sku: '2881016018702',
    barcode: '2881016018702',
    nameAr: 'كمون ناعم 70 جم',
    nameEn: 'Cumin Powder 70g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.105,
    salePrice: 0.268,
    quantityOnHand: 410,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-107',
    sku: '2881016018719',
    barcode: '2881016018719',
    nameAr: 'كمون حب 70 جم',
    nameEn: 'Cumin Seeds 70g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.105,
    salePrice: 0.268,
    quantityOnHand: 390,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-108',
    sku: '2881016018863',
    barcode: '2881016018863',
    nameAr: 'فلفل احمر ناعم 80 جم',
    nameEn: 'Red Chilli Powder 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.064,
    salePrice: 0.200,
    quantityOnHand: 250,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-109',
    sku: '2881016018894',
    barcode: '2881016018894',
    nameAr: 'سماق 90جم',
    nameEn: 'Sumac Powder 90g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.063,
    salePrice: 0.400,
    quantityOnHand: 340,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-110',
    sku: '2881016018900',
    barcode: '2881016018900',
    nameAr: 'كركم ناعم 90جم',
    nameEn: 'Turmeric Powder 90g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.113,
    salePrice: 0.200,
    quantityOnHand: 480,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-111',
    sku: '2881016019266',
    barcode: '2881016019266',
    nameAr: 'لومي حب 200 جم',
    nameEn: 'Dry Lime Whole 200g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.250,
    salePrice: 0.550,
    quantityOnHand: 200,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-112',
    sku: '2881016019433',
    barcode: '2881016019433',
    nameAr: 'كشمش ذهبي 450 جم',
    nameEn: 'Golden Raisins 450g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.720,
    salePrice: 1.000,
    quantityOnHand: 180,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-113',
    sku: '2881016018948',
    barcode: '2881016018948',
    nameAr: 'زنجبيل ناعم 80 جم',
    nameEn: 'Ginger Powder 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.075,
    salePrice: 0.300,
    quantityOnHand: 320,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-114',
    sku: '2881016018771',
    barcode: '2881016018771',
    nameAr: 'بهارات برياني حب 100 جم',
    nameEn: 'Biryani Spices Whole 100g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.100,
    salePrice: 0.500,
    quantityOnHand: 410,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-115',
    sku: '2881016018962',
    barcode: '2881016018962',
    nameAr: 'فلفل احمر بابريكا 95 جم',
    nameEn: 'Paprika Powder 95g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.095,
    salePrice: 0.400,
    quantityOnHand: 270,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-116',
    sku: '2881016019075',
    barcode: '2881016019075',
    nameAr: 'روبيان مجفف 150 جم',
    nameEn: 'Dried Shrimp 150g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 1.200,
    salePrice: 1.500,
    quantityOnHand: 150,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-117',
    sku: '2881016019013',
    barcode: '2881016019013',
    nameAr: 'فلفل احمر مجروش 60 جم',
    nameEn: 'Crushed Red Chilli 60g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.090,
    salePrice: 0.200,
    quantityOnHand: 310,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-118',
    sku: '2881016019037',
    barcode: '2881016019037',
    nameAr: 'ورق غار 30 جم',
    nameEn: 'Bay Leaves 30g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.024,
    salePrice: 0.300,
    quantityOnHand: 260,
    minQuantityAlert: 25,
    isActive: true,
  },
  {
    id: 'inv-119',
    sku: '2881016018993',
    barcode: '2881016018993',
    nameAr: 'صنوبر فاخر 50 جم',
    nameEn: 'Premium Pine Nuts 50g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.500,
    salePrice: 1.800,
    quantityOnHand: 120,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-120',
    sku: '2730703006672',
    barcode: '2730703006672',
    nameAr: 'يانسون حب 80 جم',
    nameEn: 'Aniseed Whole 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.120,
    salePrice: 0.400,
    quantityOnHand: 330,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-121',
    sku: '2881016018924',
    barcode: '2881016018924',
    nameAr: 'ملح ليمون 100 جم',
    nameEn: 'Citric Acid 100g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.060,
    salePrice: 0.200,
    quantityOnHand: 400,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-122',
    sku: '2881016019242',
    barcode: '2881016019242',
    nameAr: 'جوز هند مبشور 150 جم',
    nameEn: 'Desiccated Coconut 150g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.150,
    salePrice: 0.400,
    quantityOnHand: 220,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-123',
    sku: '2730703006648',
    barcode: '2730703006648',
    nameAr: 'سمسم محمص 90 جم',
    nameEn: 'Roasted Sesame 90g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.090,
    salePrice: 0.200,
    quantityOnHand: 360,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-124',
    sku: '2881016019334',
    barcode: '2881016019334',
    nameAr: 'جريش إماراتي 400 جم',
    nameEn: 'Emirati Jareesh 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.100,
    salePrice: 0.450,
    quantityOnHand: 280,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-125',
    sku: '2881016019358',
    barcode: '2881016019358',
    nameAr: 'عدس احمر مجروش 400 جم',
    nameEn: 'Red Split Lentils 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.100,
    salePrice: 0.450,
    quantityOnHand: 350,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-126',
    sku: '2881016019372',
    barcode: '2881016019372',
    nameAr: 'ماش اخضر مجروش 450 جم',
    nameEn: 'Green Mung Split 450g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.270,
    salePrice: 0.450,
    quantityOnHand: 210,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-127',
    sku: '2881016018870',
    barcode: '2881016018870',
    nameAr: 'صفار الزعفران 80 جم',
    nameEn: 'Saffron Yellow Powder 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.144,
    salePrice: 0.400,
    quantityOnHand: 440,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-128',
    sku: '2881016018733',
    barcode: '2881016018733',
    nameAr: 'شمر حبه حلوه 70 جم',
    nameEn: 'Fennel Seeds 70g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.042,
    salePrice: 0.250,
    quantityOnHand: 300,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-129',
    sku: '2881016018757',
    barcode: '2881016018757',
    nameAr: 'حبة البركه السوداء 70 جم',
    nameEn: 'Black Seed 70g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.042,
    salePrice: 0.250,
    quantityOnHand: 310,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-130',
    sku: '2881016018641',
    barcode: '2881016018641',
    nameAr: 'هيل ناعم 80 جم',
    nameEn: 'Cardamom Powder 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.080,
    salePrice: 0.900,
    quantityOnHand: 400,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-131',
    sku: '2881016018658',
    barcode: '2881016018658',
    nameAr: 'دارسين ناعم 80 جم',
    nameEn: 'Cinnamon Powder 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.042,
    salePrice: 0.200,
    quantityOnHand: 290,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-132',
    sku: '2881016018689',
    barcode: '2881016018689',
    nameAr: 'كزبرة ناعم 75 جم',
    nameEn: 'Coriander Powder 75g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.075,
    salePrice: 0.200,
    quantityOnHand: 360,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-133',
    sku: '2730703006571',
    barcode: '2730703006571',
    nameAr: 'هيل حب ممتاز 80 جم',
    nameEn: 'Premium Cardamom Whole 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.960,
    salePrice: 1.300,
    quantityOnHand: 280,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-134',
    sku: '2730703006572',
    barcode: '2730703006572',
    nameAr: 'هيل حب إكسترا 80 جم',
    nameEn: 'Extra Cardamom Whole 80g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.960,
    salePrice: 1.400,
    quantityOnHand: 220,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-135',
    sku: '2730703006573',
    barcode: '2730703006573',
    nameAr: 'هيل حب وسط 75 جم',
    nameEn: 'Medium Cardamom Whole 75g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.900,
    salePrice: 1.200,
    quantityOnHand: 250,
    minQuantityAlert: 25,
    isActive: true,
  },
  {
    id: 'inv-136',
    sku: '2730703006564',
    barcode: '2730703006564',
    nameAr: 'هيل امريكي رقم (1) 200 جم',
    nameEn: 'US Cardamom No.1 200g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 2.400,
    salePrice: 3.000,
    quantityOnHand: 140,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-137',
    sku: '2881016019288',
    barcode: '2881016019288',
    nameAr: 'ذرة فيشار 300 جم',
    nameEn: 'Popcorn Corn 300g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.144,
    salePrice: 0.268,
    quantityOnHand: 310,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-138',
    sku: '2850402044165',
    barcode: '2850402044165',
    nameAr: 'سمك مجفف 150 جم',
    nameEn: 'Dried Fish 150g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.120,
    salePrice: 0.500,
    quantityOnHand: 190,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-139',
    sku: '2881016019211',
    barcode: '2881016019211',
    nameAr: 'حمص مجروش 400 جم',
    nameEn: 'Split Chickpeas 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.160,
    salePrice: 0.450,
    quantityOnHand: 340,
    minQuantityAlert: 30,
    isActive: true,
  },

  // Highlighted Yellow Items
  {
    id: 'inv-140',
    sku: '1000456505011',
    barcode: '1000456505011',
    nameAr: 'حلبة حب 100 جم',
    nameEn: 'Fenugreek Seeds 100g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.047,
    salePrice: 0.175,
    quantityOnHand: 500,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-141',
    sku: '1000456505012',
    barcode: '1000456505012',
    nameAr: 'فاصوليا بيضاء 400 جم',
    nameEn: 'White Beans 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.360,
    salePrice: 0.540,
    quantityOnHand: 320,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-142',
    sku: '1000456505013',
    barcode: '1000456505013',
    nameAr: 'لوبيا بيضاء 400 جم',
    nameEn: 'Black Eyed Peas 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.360,
    salePrice: 0.500,
    quantityOnHand: 300,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-143',
    sku: '1000456505014',
    barcode: '1000456505014',
    nameAr: 'سميد ناعم 400 جم',
    nameEn: 'Fine Semolina 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.133,
    salePrice: 0.300,
    quantityOnHand: 410,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-144',
    sku: '1000456505015',
    barcode: '1000456505015',
    nameAr: 'سميد خشن 400 جم',
    nameEn: 'Coarse Semolina 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.133,
    salePrice: 0.330,
    quantityOnHand: 390,
    minQuantityAlert: 40,
    isActive: true,
  },
  {
    id: 'inv-145',
    sku: '1000456505016',
    barcode: '1000456505016',
    nameAr: 'عدس كشري 400 جم',
    nameEn: 'Brown Koshari Lentils 400g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.360,
    salePrice: 0.600,
    quantityOnHand: 270,
    minQuantityAlert: 30,
    isActive: true,
  },
  {
    id: 'inv-146',
    sku: '1000456505017',
    barcode: '1000456505017',
    nameAr: 'حب شمسي ملح 200 جم',
    nameEn: 'Salted Sunflower Seeds 200g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.160,
    salePrice: 0.300,
    quantityOnHand: 450,
    minQuantityAlert: 50,
    isActive: true,
  },
  {
    id: 'inv-147',
    sku: '1000456505018',
    barcode: '1000456505018',
    nameAr: 'حب شمسي مدخن 200 جم',
    nameEn: 'Smoked Sunflower Seeds 200g',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.160,
    salePrice: 0.350,
    quantityOnHand: 420,
    minQuantityAlert: 40,
    isActive: true,
  },

  // Special Offer Items (حبتين عرض الوليد)
  {
    id: 'inv-148',
    sku: '1000456800314',
    barcode: '1000456800314',
    nameAr: 'فلفل اسود ناعم 80 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Black Pepper Powder 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.480,
    salePrice: 0.700,
    quantityOnHand: 180,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-149',
    sku: '1000456800321',
    barcode: '1000456800321',
    nameAr: 'فلفل اسود حب 80 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Black Pepper Whole 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.480,
    salePrice: 0.700,
    quantityOnHand: 160,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-150',
    sku: '1000456800352',
    barcode: '1000456800352',
    nameAr: 'كمون ناعم 70 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Cumin Powder 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.210,
    salePrice: 0.450,
    quantityOnHand: 220,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-151',
    sku: '1000456800369',
    barcode: '1000456800369',
    nameAr: 'كمون حب 70 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Cumin Seeds 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.210,
    salePrice: 0.450,
    quantityOnHand: 210,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-152',
    sku: '1000456800338',
    barcode: '1000456800338',
    nameAr: 'قرنفل مسمار 70 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Cloves Whole 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.462,
    salePrice: 0.900,
    quantityOnHand: 140,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-153',
    sku: '1000456800406',
    barcode: '1000456800406',
    nameAr: 'سماق 90 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Sumac 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.126,
    salePrice: 0.700,
    quantityOnHand: 170,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-154',
    sku: '1000456800413',
    barcode: '1000456800413',
    nameAr: 'كركم ناعم 90 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Turmeric 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.225,
    salePrice: 0.350,
    quantityOnHand: 250,
    minQuantityAlert: 25,
    isActive: true,
  },
  {
    id: 'inv-155',
    sku: '1000270500353',
    barcode: '1000270500353',
    nameAr: 'جوز هند مبشور 150 جم 2 حبة عرض',
    nameEn: 'Coconut Shredded 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.300,
    salePrice: 0.700,
    quantityOnHand: 130,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-156',
    sku: '1000270500360',
    barcode: '1000270500360',
    nameAr: 'عدس مجروش 400 جم 2 حبة عرض',
    nameEn: 'Split Lentils 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.200,
    salePrice: 0.700,
    quantityOnHand: 190,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-157',
    sku: '1000270500384',
    barcode: '1000270500384',
    nameAr: 'كشمش ذهبي فاخر 400 جم 2 حبة عرض',
    nameEn: 'Golden Raisins 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 1.440,
    salePrice: 1.500,
    quantityOnHand: 110,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-158',
    sku: '730703006618',
    barcode: '730703006618',
    nameAr: 'حمص مجروش 400 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Chickpeas Split 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.320,
    salePrice: 0.700,
    quantityOnHand: 180,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-159',
    sku: '2881016019389',
    barcode: '2881016019389',
    nameAr: 'ماش اخضر مجروش 400 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Green Mung 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.540,
    salePrice: 0.700,
    quantityOnHand: 140,
    minQuantityAlert: 15,
    isActive: true,
  },
  {
    id: 'inv-160',
    sku: '2730703006657',
    barcode: '2730703006657',
    nameAr: 'فلفل احمر مجروش 60 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Crushed Red Chilli 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.180,
    salePrice: 0.350,
    quantityOnHand: 160,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-161',
    sku: '2730703006636',
    barcode: '2730703006636',
    nameAr: 'كزبرة ناعم 75 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Coriander Powder 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.150,
    salePrice: 0.350,
    quantityOnHand: 200,
    minQuantityAlert: 20,
    isActive: true,
  },
  {
    id: 'inv-162',
    sku: '2730703006647',
    barcode: '2730703006647',
    nameAr: 'دارسين عود 150 جم الوليد 2 حبة عرض',
    nameEn: 'Al-Waleed Cinnamon Sticks 2x Offer',
    category: 'بهارات',
    unit: 'حبة',
    unitsPerPack: 1,
    packUnit: 'حبة',
    purchasePrice: 0.450,
    salePrice: 0.700,
    quantityOnHand: 150,
    minQuantityAlert: 20,
    isActive: true,
  },
];

export const INITIAL_JOURNALS: JournalEntry[] = [];

export const INITIAL_INVOICES: Invoice[] = [];

export const DEFAULT_COMPANY_PROFILE: CompanyProfile = {
  id: 'company-logix-01',
  nameAr: 'مجموعة لوجيكس لإدارة الموارد السحابية',
  nameEn: 'LOGIX Cloud ERP Enterprise',
  tradeName: 'لوجيكس للحلول المالية والمحاسبية (LOGIX ERP)',
  legalForm: 'شركة مساهمة مقفلة (ش.م.ك)',
  taxNumber: '300012345600003',
  crNumber: '1010998877',
  crIssueDate: '2020-01-01',
  crExpiryDate: '2030-01-01',
  chamberNumber: '889900',
  vatRate: 15,
  vatType: 'QUARTERLY',
  zatcaPhase: 'PHASE_2_INTEGRATED',
  zatcaEnv: 'PRODUCTION',
  buildingNo: 'برج لوجيكس للأعمال',
  streetName: 'طريق الملك فهد',
  district: 'حي العليا',
  city: 'الرياض',
  country: 'المملكة العربية السعودية',
  postalCode: '11564',
  additionalNo: '4421',
  phone: '+966 11 456 7890',
  mobile: '+966 50 123 4567',
  email: 'info@logixerp.com',
  website: 'https://logixerp.com',
  fiscalYearStart: '2026-01-01',
  fiscalYearEnd: '2026-12-31',
  functionalCurrency: 'SAR',
  accountingBasis: 'ACCRUAL',
  inventoryCosting: 'WEIGHTED_AVERAGE',
  depreciationMethod: 'STRAIGHT_LINE',
  decimalPlaces: 2,
  generalManager: 'م. عبد العزيز بن فهد',
  financialManager: 'أ. ياسر القحطاني',
  chiefAccountant: 'أ. عبد الرحمن السعيد',
  logoUrl: '',
  headerNotes: 'نظام لوجيكس السحابي لتخطيط الموارد (LOGIX Multi-Tenant ERP)',
  footerNotes: 'الدفع خلال 30 يوماً من تاريخ استلام الفاتورة.',
  showDigitalStamp: true,
};

export const INITIAL_UNITS: UnitDefinition[] = [
  { id: 'u-1', code: 'PCS', nameAr: 'حبة / قطعة', nameEn: 'Piece', conversionFactor: 1, isBaseUnit: true, description: 'الوحدة الأساسية الفردية' },
  { id: 'u-2', code: 'CTN', nameAr: 'كرتون', nameEn: 'Carton', conversionFactor: 12, isBaseUnit: false, description: 'عبوة كرتون يحتوي على عدة حبات' },
  { id: 'u-3', code: 'PK', nameAr: 'شدة / طرد', nameEn: 'Pack', conversionFactor: 6, isBaseUnit: false, description: 'شدة بلاستيكية أو مغلفة' },
  { id: 'u-4', code: 'BOX', nameAr: 'صندوق', nameEn: 'Box', conversionFactor: 24, isBaseUnit: false, description: 'صندوق خشبي أو مقوى' },
  { id: 'u-5', code: 'DZN', nameAr: 'درزن', nameEn: 'Dozen', conversionFactor: 12, isBaseUnit: false, description: 'درزن (12 حبة)' },
  { id: 'u-6', code: 'KG', nameAr: 'كيلو جرام (كجم)', nameEn: 'Kilogram', conversionFactor: 1, isBaseUnit: true, description: 'وحدة وزن أساسية' },
  { id: 'u-7', code: 'G', nameAr: 'جرام (جم)', nameEn: 'Gram', conversionFactor: 0.001, isBaseUnit: false, description: 'وحدة جرام دقيقة' },
  { id: 'u-8', code: 'BAG', nameAr: 'شوال / خيشة', nameEn: 'Sack/Bag', conversionFactor: 50, isBaseUnit: false, description: 'كيس شوال كبير (مثلاً 50 كجم)' },
  { id: 'u-9', code: 'TON', nameAr: 'طن متري', nameEn: 'Ton', conversionFactor: 1000, isBaseUnit: false, description: 'طن متري (1000 كجم)' },
];

