import {
  Account,
  InventoryItem,
  Invoice,
  JournalEntry,
  PaymentVoucher,
  Customer,
  Supplier,
} from '../types.js';
import { supabase, toValidUUID } from './supabaseClient.js';
import { resolveToSupabaseCompanyUUID } from './supabaseService.js';
import { localDataStore } from './dataService.js';
import { cacheService } from './cacheService.js';
import { safeApiFetch } from '../utils/safeJson.js';

export interface ImportProgress {
  total: number;
  current: number;
  stage: string;
  message: string;
}

export interface FallbackStats {
  customersAutoCreated: number;
  suppliersAutoCreated: number;
  itemsAutoCreated: number;
  accountsAutoCreated: number;
  journalsAutoGenerated: number;
  journalsAutoBalanced: number;
}

export interface ImportResultReport {
  success: boolean;
  message: string;
  acceptedTotal: number;
  failedTotal: number;
  companyId: string;
  stats: {
    accounts: number;
    customers: number;
    suppliers: number;
    inventory: number;
    invoices: number;
    vouchers: number;
    journals: number;
  };
  fallbackStats?: FallbackStats;
  autoProvisionedDetails?: string[];
  errors: string[];
}

/**
 * UUID Sanitizer and ID Mapper
 * Generates valid UUIDs for legacy string IDs (e.g., "acc-1000", "inv-101", "cust-9407")
 * while maintaining referential integrity across all entities in memory.
 */
class IdSanitizerMap {
  public map = new Map<string, string>();
  private uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

  public generateUUID(): string {
    if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
      try {
        return crypto.randomUUID();
      } catch {}
    }
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }

  public isValidUUID(id: any): boolean {
    return typeof id === 'string' && this.uuidRegex.test(id.trim());
  }

  public getOrCreateUUID(rawId?: any): string {
    if (!rawId || typeof rawId !== 'string' || !rawId.trim()) {
      return this.generateUUID();
    }
    const cleanId = rawId.trim();
    if (this.map.has(cleanId)) {
      return this.map.get(cleanId)!;
    }
    if (this.isValidUUID(cleanId)) {
      this.map.set(cleanId, cleanId);
      return cleanId;
    }
    const newUuid = this.generateUUID();
    this.map.set(cleanId, newUuid);
    return newUuid;
  }

  public mapExisting(rawId: any): string | null {
    if (!rawId || typeof rawId !== 'string') return null;
    const cleanId = rawId.trim();
    if (this.map.has(cleanId)) return this.map.get(cleanId)!;
    if (this.isValidUUID(cleanId)) return cleanId;
    return null;
  }
}

/**
 * Deduplicate an array of objects by a unique key in memory,
 * keeping the newest/latest record if duplicates exist.
 */
function deduplicateLatest<T>(
  items: T[],
  getKey: (item: T) => string,
  getTimestamp?: (item: T) => number
): T[] {
  const map = new Map<string, T>();
  for (const item of items) {
    const rawKey = getKey(item);
    if (!rawKey) continue;
    const key = rawKey.trim().toUpperCase();
    if (!map.has(key)) {
      map.set(key, item);
    } else {
      if (getTimestamp) {
        const prevTime = getTimestamp(map.get(key)!);
        const currTime = getTimestamp(item);
        if (currTime >= prevTime) {
          map.set(key, item);
        }
      } else {
        // Last one in the file takes precedence as latest update
        map.set(key, item);
      }
    }
  }
  return Array.from(map.values());
}

export class ERPBackupImportService {
  /**
   * Universal alias for importBackupData to maintain backward and forward compatibility
   */
  public static async importBackupData(
    jsonInput: string | any,
    targetCompanyId: string,
    onProgress?: (progress: ImportProgress) => void
  ): Promise<ImportResultReport> {
    return this.importCompanyJsonData(targetCompanyId, jsonInput, onProgress);
  }

  /**
   * Imports ERP Backup JSON into Supabase and local storage with strict tenant scoping:
   * 1. Ignores legacy company IDs like "company-kw-01", forcing active tenant UUID.
   * 2. Sanitizes old IDs ("acc-1000", "inv-101", "cust-9407") into valid UUIDs with an in-memory mapping.
   * 3. Pre-queries existing Supabase items/customers/suppliers/accounts to link with existing records.
   * 4. Memory deduplication: keeps newest record for duplicate reference numbers.
   * 5. Safe sequential processing: Batches of 25 with correct 'id' onConflict and mandatory 'name' column.
   * 6. Persists data to localDataStore and cacheService for immediate offline and UI rendering.
   */
  public static async importCompanyJsonData(
    targetCompanyId: string,
    jsonInput: string | any,
    onProgress?: (progress: ImportProgress) => void
  ): Promise<ImportResultReport> {
    const report: ImportResultReport = {
      success: false,
      message: '',
      acceptedTotal: 0,
      failedTotal: 0,
      companyId: '',
      stats: {
        accounts: 0,
        customers: 0,
        suppliers: 0,
        inventory: 0,
        invoices: 0,
        vouchers: 0,
        journals: 0,
      },
      errors: [],
    };

    let localStoreSnapshot: any = null;

    try {
      const parsed = typeof jsonInput === 'string' ? JSON.parse(jsonInput) : jsonInput;
      if (!parsed || typeof parsed !== 'object') {
        report.message = 'ملف JSON غير صالح أو فارغ';
        return report;
      }

      // ==============================================================================
      // 1. Force Active Company UUID (Strict Scoping & Ignore "company-kw-01")
      // ==============================================================================
      let activeCompanyUUID = resolveToSupabaseCompanyUUID(targetCompanyId) || targetCompanyId;
      if (!activeCompanyUUID || activeCompanyUUID === 'company-kw-01') {
        const savedTenant = typeof window !== 'undefined' ? localStorage.getItem('supabase_company_id') : null;
        activeCompanyUUID = resolveToSupabaseCompanyUUID(savedTenant) || savedTenant || '20000000-0000-0000-0000-000000000001';
      }

      // Ensure activeCompanyUUID is a valid UUID
      const idSanitizer = new IdSanitizerMap();
      if (!idSanitizer.isValidUUID(activeCompanyUUID)) {
        activeCompanyUUID = toValidUUID(activeCompanyUUID);
      }
      report.companyId = activeCompanyUUID;

      const rawData = parsed.data && typeof parsed.data === 'object' ? parsed.data : parsed;

      // Extract and normalize raw entities (supporting all schema naming variants)
      const rawAccounts: Account[] = rawData.accounts || rawData.chart_of_accounts || rawData.chartOfAccounts || [];
      const rawCustomers: Customer[] = rawData.customers || rawData.clients || [];
      const rawSuppliers: Supplier[] = rawData.suppliers || rawData.vendors || [];
      const rawInventory: InventoryItem[] = rawData.inventory || rawData.items || rawData.products || rawData.articles || [];
      const rawInvoices: Invoice[] = rawData.invoices || rawData.sales_invoices || rawData.salesInvoices || [];
      const rawVouchers: PaymentVoucher[] = rawData.vouchers || rawData.payment_vouchers || rawData.paymentVouchers || rawData.receipts || [];
      const rawJournals: JournalEntry[] = rawData.journals || rawData.journal_entries || rawData.journalEntries || [];

      // ==============================================================================
      // 2. In-Memory Deduplication
      //    Keep newest version of any record sharing the same reference number
      // ==============================================================================
      const dedupeTimestamp = (item: any) => {
        const ts = item.updatedAt || item.updated_at || item.date || item.createdAt || item.created_at;
        return ts ? new Date(ts).getTime() : 0;
      };

      const accounts = deduplicateLatest(
        rawAccounts,
        (a) => a.code || a.id,
        dedupeTimestamp
      );

      const customers = deduplicateLatest(
        rawCustomers,
        (c: any) => c.code || c.phone || c.id,
        dedupeTimestamp
      );

      const suppliers = deduplicateLatest(
        rawSuppliers,
        (s: any) => s.code || s.phone || s.id,
        dedupeTimestamp
      );

      const inventory = deduplicateLatest(
        rawInventory,
        (item: any) => item.sku || item.code || item.barcode || item.id,
        dedupeTimestamp
      );

      const invoices = deduplicateLatest(
        rawInvoices,
        (inv: any) => inv.invoiceNumber || inv.invoice_number || inv.id,
        dedupeTimestamp
      );

      const vouchers = deduplicateLatest(
        rawVouchers,
        (v: any) => v.voucherNumber || v.voucher_number || v.id,
        dedupeTimestamp
      );

      const journals = deduplicateLatest(
        rawJournals,
        (j: any) => j.entryNumber || j.entry_number || j.id,
        dedupeTimestamp
      );

      // ==============================================================================
      // 3. SMART AUTO-PROVISIONING & FALLBACK VALUES ENGINE (المعالجة الذكية للبيانات)
      // Automatically creates missing entities (Accounts, Customers, Suppliers, Items)
      // and synthesizes balanced double-entry journals for unposted invoices/vouchers.
      // NEVER aborts or rejects imports due to missing references!
      // ==============================================================================
      const fallbackStats: FallbackStats = {
        customersAutoCreated: 0,
        suppliersAutoCreated: 0,
        itemsAutoCreated: 0,
        accountsAutoCreated: 0,
        journalsAutoGenerated: 0,
        journalsAutoBalanced: 0,
      };
      const autoProvisionedDetails: string[] = [];

      // 3.1. Auto-Provision Essential Standard Accounts if missing
      const existingAccountCodes = new Set(accounts.map((a) => a.code).filter(Boolean));
      const standardAccountsToEnsure: Array<{
        code: string;
        nameAr: string;
        category: Account['category'];
        normalBalance: 'DEBIT' | 'CREDIT';
      }> = [
        { code: '1110', nameAr: 'الصندوق والخزينة الرئيسية', category: 'ASSET', normalBalance: 'DEBIT' },
        { code: '1120', nameAr: 'البنك والحسابات الجارية', category: 'ASSET', normalBalance: 'DEBIT' },
        { code: '1210', nameAr: 'العملاء والمدينون التجاريون', category: 'ASSET', normalBalance: 'DEBIT' },
        { code: '1250', nameAr: 'ضريبة القيمة المضافة المدخلات (استرداد)', category: 'ASSET', normalBalance: 'DEBIT' },
        { code: '1310', nameAr: 'مخزون البضائع والمستودعات', category: 'ASSET', normalBalance: 'DEBIT' },
        { code: '2110', nameAr: 'الموردون والدائنون التجاريون', category: 'LIABILITY', normalBalance: 'CREDIT' },
        { code: '2150', nameAr: 'ضريبة القيمة المضافة المخرجات (مستحقة)', category: 'LIABILITY', normalBalance: 'CREDIT' },
        { code: '3110', nameAr: 'رأس مال المنشأة', category: 'EQUITY', normalBalance: 'CREDIT' },
        { code: '3999', nameAr: 'حساب تسويات وفروقات القيود المستوردة', category: 'EQUITY', normalBalance: 'CREDIT' },
        { code: '4101', nameAr: 'إيرادات المبيعات والخدمات', category: 'REVENUE', normalBalance: 'CREDIT' },
        { code: '5101', nameAr: 'تكلفة البضاعة المباعة والمشتريات', category: 'EXPENSE', normalBalance: 'DEBIT' },
      ];

      for (const stdAcc of standardAccountsToEnsure) {
        if (!existingAccountCodes.has(stdAcc.code)) {
          const accId = idSanitizer.getOrCreateUUID(`acc-std-${stdAcc.code}`);
          accounts.push({
            id: accId,
            code: stdAcc.code,
            nameAr: stdAcc.nameAr,
            nameEn: '',
            category: stdAcc.category,
            normalBalance: stdAcc.normalBalance,
            level: 4,
            type: 'DETAIL',
            balance: 0,
            currentBalance: 0,
            isActive: true,
            is_fallback: true,
          } as any);
          existingAccountCodes.add(stdAcc.code);
          fallbackStats.accountsAutoCreated++;
          autoProvisionedDetails.push(`تم تزويد حساب النظام القياسي تلقائياً: ${stdAcc.nameAr} (${stdAcc.code})`);
        }
      }

      // 3.2. Auto-Provision Fallback Customers, Suppliers & Inventory Items for Invoices
      const existingCustomerIds = new Set(customers.map((c) => c.id).filter(Boolean));
      const existingCustomerCodes = new Set(customers.map((c: any) => c.code).filter(Boolean));
      const existingCustomerNames = new Set(customers.map((c) => c.nameAr?.trim()).filter(Boolean));

      const existingSupplierIds = new Set(suppliers.map((s) => s.id).filter(Boolean));
      const existingSupplierCodes = new Set(suppliers.map((s: any) => s.code).filter(Boolean));
      const existingSupplierNames = new Set(suppliers.map((s) => s.nameAr?.trim()).filter(Boolean));

      const existingItemIds = new Set(inventory.map((i) => i.id).filter(Boolean));
      const existingItemSkus = new Set(inventory.map((i: any) => i.sku || i.code).filter(Boolean));
      const existingItemNames = new Set(inventory.map((i) => i.nameAr?.trim()).filter(Boolean));

      invoices.forEach((inv, invIdx) => {
        const isSales = inv.type === 'SALES' || inv.type === 'SALES_RETURN';
        const rawEntityId = inv.entityId || (inv as any).customerId || (inv as any).supplierId;
        const rawEntityName = inv.entityNameAr || (inv as any).customerName || (inv as any).supplierName || '';

        if (isSales) {
          const hasCustomer =
            (rawEntityId && (existingCustomerIds.has(rawEntityId) || existingCustomerCodes.has(rawEntityId))) ||
            (rawEntityName && existingCustomerNames.has(rawEntityName.trim()));

          if (!hasCustomer) {
            const fallbackCustId = idSanitizer.getOrCreateUUID(rawEntityId || `cust-auto-${inv.invoiceNumber || invIdx}`);
            const fallbackCustName = rawEntityName.trim() || `عميل افتراضي (${inv.invoiceNumber || `INV-${invIdx + 1}`})`;
            const fallbackCustCode = `CUST-AUTO-${String(customers.length + 1).padStart(4, '0')}`;

            customers.push({
              id: fallbackCustId,
              code: fallbackCustCode,
              nameAr: fallbackCustName,
              nameEn: '',
              phone: (inv as any).phone || '',
              address: '',
              city: 'الكويت',
              balance: 0,
              openingBalance: 0,
              isActive: true,
              is_fallback: true,
              notes: 'تم إنشاؤه تلقائياً كبيان افتراضي أثناء الاستيراد - يمكن تعديله من شاشة العملاء',
            } as any);

            existingCustomerIds.add(fallbackCustId);
            existingCustomerCodes.add(fallbackCustCode);
            existingCustomerNames.add(fallbackCustName);
            inv.entityId = fallbackCustId;
            inv.entityNameAr = fallbackCustName;
            fallbackStats.customersAutoCreated++;
            autoProvisionedDetails.push(`تم إنشاء عميل افتراضي "${fallbackCustName}" للفاتورة ${inv.invoiceNumber || ''}`);
          }
        } else {
          // Purchases
          const hasSupplier =
            (rawEntityId && (existingSupplierIds.has(rawEntityId) || existingSupplierCodes.has(rawEntityId))) ||
            (rawEntityName && existingSupplierNames.has(rawEntityName.trim()));

          if (!hasSupplier) {
            const fallbackSuppId = idSanitizer.getOrCreateUUID(rawEntityId || `supp-auto-${inv.invoiceNumber || invIdx}`);
            const fallbackSuppName = rawEntityName.trim() || `مورد افتراضي (${inv.invoiceNumber || `PUR-${invIdx + 1}`})`;
            const fallbackSuppCode = `SUPP-AUTO-${String(suppliers.length + 1).padStart(4, '0')}`;

            suppliers.push({
              id: fallbackSuppId,
              code: fallbackSuppCode,
              nameAr: fallbackSuppName,
              nameEn: '',
              phone: '',
              address: '',
              balance: 0,
              isActive: true,
              is_fallback: true,
              notes: 'تم إنشاؤه تلقائياً كبيان افتراضي أثناء الاستيراد - يمكن تعديله من شاشة الموردين',
            } as any);

            existingSupplierIds.add(fallbackSuppId);
            existingSupplierCodes.add(fallbackSuppCode);
            existingSupplierNames.add(fallbackSuppName);
            inv.entityId = fallbackSuppId;
            inv.entityNameAr = fallbackSuppName;
            fallbackStats.suppliersAutoCreated++;
            autoProvisionedDetails.push(`تم إنشاء مورد افتراضي "${fallbackSuppName}" للفاتورة ${inv.invoiceNumber || ''}`);
          }
        }

        // Ensure lines exist and items exist
        if (!Array.isArray(inv.lines) || inv.lines.length === 0) {
          const fallbackTotal = Number(inv.totalAmount || inv.subtotal || 0);
          inv.lines = [
            {
              id: `line-${invIdx}-1`,
              itemId: '',
              description: `بند افتراضي لفاتورة ${inv.invoiceNumber || invIdx + 1}`,
              quantity: 1,
              unitPrice: fallbackTotal,
              total: fallbackTotal,
            } as any,
          ];
        }

        inv.lines.forEach((line: any, lineIdx: number) => {
          const rawItemId = line.itemId || line.productId || line.id;
          const rawSku = line.sku || (line as any).code;
          const rawName = line.itemName || line.nameAr || line.description || '';

          const hasItem =
            (rawItemId && existingItemIds.has(rawItemId)) ||
            (rawSku && existingItemSkus.has(rawSku)) ||
            (rawName && existingItemNames.has(rawName.trim()));

          if (!hasItem) {
            const fallbackItemId = idSanitizer.getOrCreateUUID(rawItemId || `item-auto-${inv.invoiceNumber || invIdx}-${lineIdx}`);
            const fallbackSku = rawSku || `SKU-AUTO-${String(inventory.length + 1).padStart(4, '0')}`;
            const fallbackItemName = rawName.trim() || `صنف افتراضي (${fallbackSku})`;

            inventory.push({
              id: fallbackItemId,
              sku: fallbackSku,
              nameAr: fallbackItemName,
              nameEn: '',
              barcode: (line as any).barcode || '',
              category: 'أصناف افتراضية مستوردة',
              unit: line.unit || 'حبة',
              purchasePrice: Number(line.costPrice || line.unitPrice || 0),
              costPrice: Number(line.costPrice || line.unitPrice || 0),
              salePrice: Number(line.unitPrice || 0),
              quantityOnHand: Number(line.quantity || 0),
              minQuantityAlert: 10,
              isActive: true,
              is_fallback: true,
              notes: 'تم إنشاؤه تلقائياً كبيان افتراضي أثناء الاستيراد - يمكن تعديله من شاشة الأصناف',
            } as any);

            existingItemIds.add(fallbackItemId);
            existingItemSkus.add(fallbackSku);
            existingItemNames.add(fallbackItemName);
            line.itemId = fallbackItemId;
            line.sku = fallbackSku;
            line.itemName = fallbackItemName;
            fallbackStats.itemsAutoCreated++;
            autoProvisionedDetails.push(`تم إنشاء صنف افتراضي "${fallbackItemName}" (${fallbackSku})`);
          }
        });
      });

      // 3.3. Auto-Generate Balanced Double-Entry Journals for Invoices & Vouchers that lack journals
      const linkedJournalRefs = new Set<string>();
      journals.forEach((j) => {
        if (j.reference) linkedJournalRefs.add(j.reference);
        if ((j as any).sourceId) linkedJournalRefs.add((j as any).sourceId);
        if (j.id) linkedJournalRefs.add(j.id);
      });

      invoices.forEach((inv, invIdx) => {
        const invRef = inv.invoiceNumber || inv.id;
        const alreadyHasJournal =
          (inv.journalEntryId && linkedJournalRefs.has(inv.journalEntryId)) ||
          linkedJournalRefs.has(invRef) ||
          linkedJournalRefs.has(inv.id);

        if (!alreadyHasJournal) {
          const isSales = inv.type === 'SALES' || inv.type === 'SALES_RETURN';
          const subtotal = Number(inv.subtotal || inv.totalAmount || 0);
          const tax = Number(inv.taxAmount || 0);
          const total = Number(inv.totalAmount || subtotal + tax);
          const jvId = idSanitizer.getOrCreateUUID(`jv-gen-${invRef}`);
          const jvNumber = `JV-AUTO-${inv.invoiceNumber || invIdx + 1}`;
          const dateStr = inv.date || new Date().toISOString().split('T')[0];

          let lines: any[] = [];
          if (isSales) {
            const debitAcc = inv.paymentMethod === 'CASH' ? '1110' : '1210';
            lines = [
              {
                id: `line-${jvId}-1`,
                accountCode: debitAcc,
                accountNameAr: debitAcc === '1110' ? 'الصندوق والخزينة الرئيسية' : 'العملاء والمدينون التجاريون',
                debit: total,
                credit: 0,
                memo: `إثبات مديونية/مقبوضات فاتورة المبيعات ${inv.invoiceNumber}`,
              },
              {
                id: `line-${jvId}-2`,
                accountCode: '4101',
                accountNameAr: 'إيرادات المبيعات والخدمات',
                debit: 0,
                credit: subtotal,
                memo: `إثبات إيراد مبيعات ${inv.invoiceNumber}`,
              },
            ];
            if (tax > 0) {
              lines.push({
                id: `line-${jvId}-3`,
                accountCode: '2150',
                accountNameAr: 'ضريبة القيمة المضافة المخرجات (مستحقة)',
                debit: 0,
                credit: tax,
                memo: `ضريبة القيمة المضافة ${inv.invoiceNumber}`,
              });
            }
          } else {
            // Purchase
            const creditAcc = inv.paymentMethod === 'CASH' ? '1110' : '2110';
            lines = [
              {
                id: `line-${jvId}-1`,
                accountCode: '5101',
                accountNameAr: 'تكلفة البضاعة المباعة والمشتريات',
                debit: subtotal,
                credit: 0,
                memo: `إثبات مشتريات فاتورة ${inv.invoiceNumber}`,
              },
              {
                id: `line-${jvId}-2`,
                accountCode: creditAcc,
                accountNameAr: creditAcc === '1110' ? 'الصندوق والخزينة الرئيسية' : 'الموردون والدائنون التجاريون',
                debit: 0,
                credit: total,
                memo: `إثبات استحقاق مورد/سداد مشتريات ${inv.invoiceNumber}`,
              },
            ];
            if (tax > 0) {
              lines.push({
                id: `line-${jvId}-3`,
                accountCode: '1250',
                accountNameAr: 'ضريبة القيمة المضافة المدخلات (استرداد)',
                debit: tax,
                credit: 0,
                memo: `ضريبة القيمة المضافة المستردة ${inv.invoiceNumber}`,
              });
            }
          }

          const newJv: JournalEntry = {
            id: jvId,
            entryNumber: jvNumber,
            date: dateStr,
            reference: inv.invoiceNumber || inv.id,
            description: `قيد ترحيل آلي متوازن لفاتورة ${isSales ? 'مبيعات' : 'مشتريات'} ${inv.invoiceNumber || ''}`,
            status: 'POSTED',
            lines,
            totalDebit: total,
            totalCredit: total,
            createdAt: new Date().toISOString(),
            postedAt: new Date().toISOString(),
            isAutoGenerated: true,
            sourceModule: isSales ? 'SALES_INVOICE' : 'PURCHASE_INVOICE',
            sourceId: inv.id,
          };

          journals.push(newJv);
          linkedJournalRefs.add(inv.invoiceNumber);
          linkedJournalRefs.add(inv.id);
          inv.journalEntryId = jvId;
          fallbackStats.journalsAutoGenerated++;
          autoProvisionedDetails.push(`تم توليد قيد محاسبي متوازن آلياً للفاتورة ${inv.invoiceNumber || ''}`);
        }
      });

      // Generate missing balanced journals for Vouchers
      vouchers.forEach((v, vIdx) => {
        const vRef = v.voucherNumber || v.id;
        const alreadyHasJournal =
          (v.journalEntryId && linkedJournalRefs.has(v.journalEntryId)) ||
          linkedJournalRefs.has(vRef) ||
          linkedJournalRefs.has(v.id);

        if (!alreadyHasJournal) {
          const isReceipt = v.type === 'RECEIPT';
          const amt = Number(v.amount || 0);
          const jvId = idSanitizer.getOrCreateUUID(`jv-vch-${vRef}`);
          const jvNumber = `JV-VCH-${v.voucherNumber || vIdx + 1}`;
          const dateStr = v.date || new Date().toISOString().split('T')[0];

          let lines: any[] = [];
          if (isReceipt) {
            lines = [
              {
                id: `line-${jvId}-1`,
                accountCode: v.accountCode || '1110',
                accountNameAr: 'الصندوق والخزينة الرئيسية',
                debit: amt,
                credit: 0,
                memo: `قبض نقدي بموجب سند قبض ${v.voucherNumber || ''}`,
              },
              {
                id: `line-${jvId}-2`,
                accountCode: '1210',
                accountNameAr: 'العملاء والمدينون التجاريون',
                debit: 0,
                credit: amt,
                memo: `تسوية مديونية عميل سند قبض ${v.voucherNumber || ''}`,
              },
            ];
          } else {
            lines = [
              {
                id: `line-${jvId}-1`,
                accountCode: '2110',
                accountNameAr: 'الموردون والدائنون التجاريون',
                debit: amt,
                credit: 0,
                memo: `سداد مستحقات مورد بسند صرف ${v.voucherNumber || ''}`,
              },
              {
                id: `line-${jvId}-2`,
                accountCode: v.accountCode || '1110',
                accountNameAr: 'الصندوق والخزينة الرئيسية',
                debit: 0,
                credit: amt,
                memo: `صرف من الخزينة/البنك بسند صرف ${v.voucherNumber || ''}`,
              },
            ];
          }

          const newJv: JournalEntry = {
            id: jvId,
            entryNumber: jvNumber,
            date: dateStr,
            reference: v.voucherNumber || v.id,
            description: `قيد ترحيل آلي متوازن لسند ${isReceipt ? 'القبض' : 'الصرف'} ${v.voucherNumber || ''}`,
            status: 'POSTED',
            lines,
            totalDebit: amt,
            totalCredit: amt,
            createdAt: new Date().toISOString(),
            postedAt: new Date().toISOString(),
            isAutoGenerated: true,
            sourceModule: isReceipt ? 'RECEIPT' : 'PAYMENT',
            sourceId: v.id,
          };

          journals.push(newJv);
          linkedJournalRefs.add(v.voucherNumber);
          linkedJournalRefs.add(v.id);
          v.journalEntryId = jvId;
          fallbackStats.journalsAutoGenerated++;
          autoProvisionedDetails.push(`تم توليد قيد محاسبي متوازن لسند ${v.voucherNumber || ''}`);
        }
      });

      // 3.4. Smart Auto-Balancing for existing journals: NEVER reject or abort!
      for (let idx = 0; idx < journals.length; idx++) {
        const jv = journals[idx];
        const lines = Array.isArray(jv.lines) ? jv.lines : [];
        let sumDebit = 0;
        let sumCredit = 0;
        if (lines.length > 0) {
          sumDebit = lines.reduce((s: number, l: any) => s + (Number(l.debit) || 0), 0);
          sumCredit = lines.reduce((s: number, l: any) => s + (Number(l.credit) || 0), 0);
        } else {
          sumDebit = Number(jv.totalDebit) || 0;
          sumCredit = Number(jv.totalCredit) || 0;
        }

        const diff = Math.abs(sumDebit - sumCredit);
        if (diff > 0.001) {
          // Imbalance detected: Auto-balance using Suspense Account 3999
          if (sumDebit > sumCredit) {
            lines.push({
              id: `bal-${idx}-cr`,
              accountCode: '3999',
              accountNameAr: 'حساب تسويات وفروقات القيود المستوردة',
              debit: 0,
              credit: Number(diff.toFixed(3)),
              memo: `موازنة آلية لفارق استيراد (${diff.toFixed(3)})`,
            });
            jv.totalDebit = sumDebit;
            jv.totalCredit = sumDebit;
          } else {
            lines.push({
              id: `bal-${idx}-dr`,
              accountCode: '3999',
              accountNameAr: 'حساب تسويات وفروقات القيود المستوردة',
              debit: Number(diff.toFixed(3)),
              credit: 0,
              memo: `موازنة آلية لفارق استيراد (${diff.toFixed(3)})`,
            });
            jv.totalDebit = sumCredit;
            jv.totalCredit = sumCredit;
          }
          jv.lines = lines;
          jv.notes = (jv.notes ? jv.notes + ' | ' : '') + `[تمت موازنة القيد آلياً عبر حساب التسويات المؤقت 3999 لفارق ${diff.toFixed(3)}]`;
          fallbackStats.journalsAutoBalanced++;
          autoProvisionedDetails.push(`تمت موازنة القيد ${jv.entryNumber || idx + 1} آلياً عبر حساب التسويات المعلقة 3999`);
        }
      }

      // Snapshot existing local state for atomic rollback in case of error
      const localStoreSnapshot = {
        accounts: JSON.parse(JSON.stringify(localDataStore.getAccounts())),
        customers: JSON.parse(JSON.stringify(localDataStore.getCustomers())),
        suppliers: JSON.parse(JSON.stringify(localDataStore.getSuppliers())),
        inventory: JSON.parse(JSON.stringify(localDataStore.getInventory())),
        invoices: JSON.parse(JSON.stringify(localDataStore.getInvoices())),
        vouchers: JSON.parse(JSON.stringify(localDataStore.getVouchers())),
        journals: JSON.parse(JSON.stringify(localDataStore.getJournals())),
      };

      // Pre-query existing Supabase records to reuse existing UUIDs where code/SKU matches
      try {
        const [exItems, exCusts, exSupps, exAccs] = await Promise.all([
          supabase.from('items').select('id, code, sku').eq('company_id', activeCompanyUUID),
          supabase.from('customers').select('id, code').eq('company_id', activeCompanyUUID),
          supabase.from('suppliers').select('id, code').eq('company_id', activeCompanyUUID),
          supabase.from('chart_of_accounts').select('id, code').eq('company_id', activeCompanyUUID),
        ]);

        if (exItems.data) {
          for (const row of exItems.data) {
            if (row.code) idSanitizer.map.set(`code-${row.code}`, row.id);
            if (row.sku) idSanitizer.map.set(`sku-${row.sku}`, row.id);
          }
        }
        if (exCusts.data) {
          for (const row of exCusts.data) {
            if (row.code) idSanitizer.map.set(`custcode-${row.code}`, row.id);
          }
        }
        if (exSupps.data) {
          for (const row of exSupps.data) {
            if (row.code) idSanitizer.map.set(`suppcode-${row.code}`, row.id);
          }
        }
        if (exAccs.data) {
          for (const row of exAccs.data) {
            if (row.code) idSanitizer.map.set(`acccode-${row.code}`, row.id);
          }
        }
      } catch (exErr) {
        console.warn('Pre-query existing records note:', exErr);
      }

      // Pre-register IDs in ID Sanitizer Map to preserve relational links
      accounts.forEach((acc, index) => {
        const existingId = acc.code ? idSanitizer.mapExisting(`acccode-${acc.code}`) : null;
        const uid = existingId || idSanitizer.getOrCreateUUID(acc.id || `acc-${acc.code || index}`);
        if (acc.id) idSanitizer.map.set(acc.id, uid);
        if (acc.code) idSanitizer.map.set(acc.code, uid);
      });

      customers.forEach((c, index) => {
        const existingId = (c as any).code ? idSanitizer.mapExisting(`custcode-${(c as any).code}`) : null;
        const uid = existingId || idSanitizer.getOrCreateUUID(c.id || `cust-${(c as any).code || index}`);
        if (c.id) idSanitizer.map.set(c.id, uid);
      });

      suppliers.forEach((s, index) => {
        const existingId = (s as any).code ? idSanitizer.mapExisting(`suppcode-${(s as any).code}`) : null;
        const uid = existingId || idSanitizer.getOrCreateUUID(s.id || `supp-${(s as any).code || index}`);
        if (s.id) idSanitizer.map.set(s.id, uid);
      });

      inventory.forEach((item, index) => {
        const existingId = (item.sku && idSanitizer.mapExisting(`sku-${item.sku}`)) ||
                           ((item as any).code && idSanitizer.mapExisting(`code-${(item as any).code}`));
        const uid = existingId || idSanitizer.getOrCreateUUID(item.id || item.sku || `item-${index}`);
        if (item.id) idSanitizer.map.set(item.id, uid);
      });

      invoices.forEach((inv, index) => {
        const uid = idSanitizer.getOrCreateUUID(inv.id || `inv-${index}`);
        if (inv.id) idSanitizer.map.set(inv.id, uid);
      });

      vouchers.forEach((v, index) => {
        const uid = idSanitizer.getOrCreateUUID(v.id || `vch-${index}`);
        if (v.id) idSanitizer.map.set(v.id, uid);
      });

      journals.forEach((j, index) => {
        const uid = idSanitizer.getOrCreateUUID(j.id || `jv-${index}`);
        if (j.id) idSanitizer.map.set(j.id, uid);
      });

      const totalSteps =
        accounts.length +
        customers.length +
        suppliers.length +
        inventory.length +
        invoices.length +
        vouchers.length +
        journals.length;

      let currentStep = 0;
      const updateProgress = (stage: string, message: string, increment: number = 0) => {
        currentStep += increment;
        if (onProgress) {
          onProgress({
            total: totalSteps > 0 ? totalSteps : 1,
            current: Math.min(currentStep, totalSteps > 0 ? totalSteps : 1),
            stage,
            message,
          });
        }
      };

      updateProgress('START', 'بدء فحص وتطهير البيانات...', 0);

      // ==============================================================================
      // 3. Prepare Payloads with UUID Sanitization & Mandatory DB Constraints
      // ==============================================================================

      // 3.1 Chart of Accounts (Supabase chart_of_accounts: id, company_id, code, name_ar, name_en, category, ...)
      const accountsPayload = accounts.map((acc, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(acc.id || `acc-${acc.code || index}`);
        const parentId = acc.parentId ? idSanitizer.getOrCreateUUID(acc.parentId) : null;
        const accName = acc.nameAr || (acc as any).name || (acc as any).name_ar || 'حساب مستورد';
        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          code: acc.code || `ACC-${String(index + 1).padStart(4, '0')}`,
          name_ar: accName,
          name_en: acc.nameEn || '',
          category: acc.category || 'ASSET',
          normal_balance: acc.normalBalance || (acc as any).normal_balance || 'DEBIT',
          level: acc.level || 1,
          type: acc.type || 'DETAIL',
          parent_id: parentId,
          balance: Number(acc.balance || 0),
          current_balance: Number(acc.currentBalance ?? acc.balance ?? 0),
          is_active: true,
          updated_at: new Date().toISOString(),
        };
      });

      // 3.2 Customers (Supabase customers: id, company_id, code, name [NOT NULL], name_ar, name_en, balance, ...)
      const customersPayload = customers.map((c, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(c.id || `cust-${(c as any).code || index}`);
        const customerName = c.nameAr || (c as any).name || (c as any).name_ar || 'عميل مستورد';
        const customerCode = (c as any).code || `CUST-${String(index + 1).padStart(4, '0')}`;
        const custOpeningBal = Number(c.openingBalance ?? (c as any).opening_balance ?? (c as any).balance ?? 0);
        const custBalance = Number((c as any).balance ?? (c as any).current_balance ?? custOpeningBal ?? 0);
        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          code: customerCode,
          name: customerName,
          name_ar: customerName,
          name_en: c.nameEn || '',
          phone: c.phone || '',
          tax_number: c.taxNumber || (c as any).tax_number || '',
          address: c.address || '',
          city: (c as any).city || 'الكويت',
          balance: custBalance,
          current_balance: custBalance,
          opening_balance: custOpeningBal,
          is_active: (c as any).isActive ?? (c as any).is_active ?? true,
          raw_data: {
            ...c,
            id: sanitizedId,
            code: customerCode,
            nameAr: customerName,
            openingBalance: custOpeningBal,
            openingBalanceDate: (c as any).openingBalanceDate || '2026-07-01',
            companyId: activeCompanyUUID,
          },
          updated_at: new Date().toISOString(),
        };
      });

      // 3.3 Suppliers (Supabase suppliers: id, company_id, code, name, name_ar, name_en, phone, balance, ...)
      const suppliersPayload = suppliers.map((s, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(s.id || `supp-${(s as any).code || index}`);
        const supplierName = s.nameAr || (s as any).name || (s as any).name_ar || 'مورد مستورد';
        const supplierCode = (s as any).code || `SUPP-${String(index + 1).padStart(4, '0')}`;
        const suppOpeningBal = Number(s.openingBalance ?? (s as any).opening_balance ?? (s as any).balance ?? 0);
        const suppBalance = Number((s as any).balance ?? (s as any).current_balance ?? suppOpeningBal ?? 0);
        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          code: supplierCode,
          name: supplierName,
          name_ar: supplierName,
          name_en: s.nameEn || '',
          phone: s.phone || '',
          address: s.address || '',
          city: (s as any).city || 'الكويت',
          balance: suppBalance,
          current_balance: suppBalance,
          raw_data: {
            ...s,
            id: sanitizedId,
            code: supplierCode,
            nameAr: supplierName,
            openingBalance: suppOpeningBal,
            openingBalanceDate: (s as any).openingBalanceDate || '2026-07-01',
            companyId: activeCompanyUUID,
          },
          updated_at: new Date().toISOString(),
        };
      });

      // 3.4 Inventory Items (Supabase items: id, company_id, code, sku, name [NOT NULL], item_name, name_ar, ...)
      const itemsPayload = inventory.map((item, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(item.id || item.sku || (item as any).code || `item-${index}`);
        const itemName = item.nameAr || (item as any).name || (item as any).name_ar || 'صنف مستورد';
        const itemCode = item.sku || (item as any).code || (item as any).barcode || `SKU-${String(index + 1).padStart(4, '0')}`;
        const costPrice = Number(item.purchasePrice || (item as any).costPrice || (item as any).cost_price || 0);
        const salePrice = Number(item.salePrice || (item as any).selling_price || (item as any).sale_price || 0);
        const currentBalance = Number(item.quantityOnHand ?? (item as any).current_balance ?? (item as any).qty_on_hand ?? 0);
        const minLimit = Number(item.minQuantityAlert ?? (item as any).min_limit ?? 10);
        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          code: itemCode,
          sku: itemCode,
          barcode: item.barcode || (item as any).barcode || '',
          name: itemName,
          item_name: itemName,
          name_ar: itemName,
          name_en: item.nameEn || '',
          category: item.category || 'عام',
          unit: item.unit || 'حبة',
          cost_price: costPrice,
          sale_price: salePrice,
          selling_price: salePrice,
          current_balance: currentBalance,
          qty_on_hand: currentBalance,
          min_limit: minLimit,
          is_active: (item as any).isActive ?? (item as any).is_active ?? true,
          raw_data: {
            ...item,
            id: sanitizedId,
            sku: itemCode,
            nameAr: itemName,
            companyId: activeCompanyUUID,
          },
          updated_at: new Date().toISOString(),
        };
      });

      // 3.5 Invoices
      const invoicesPayload = invoices.map((inv, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(inv.id || `inv-${index}`);
        const customerId = inv.entityId ? idSanitizer.getOrCreateUUID(inv.entityId) : null;
        const subtotal = Number(inv.subtotal || 0);
        const taxAmount = Number(inv.vatTotal ?? (inv as any).taxAmount ?? 0);
        const totalAmount = Number(inv.grandTotal ?? (inv as any).totalAmount ?? (subtotal + taxAmount));
        const paidAmount = Number(inv.paidAmount || 0);
        const dueAmount = Number(inv.dueAmount || Math.max(0, totalAmount - paidAmount));
        const invoiceNumber = inv.invoiceNumber || (inv as any).invoice_number || `INV-${String(index + 1).padStart(4, '0')}`;

        // Sanitize item IDs inside lines
        const sanitizedLines = (inv.lines || (inv as any).items || []).map((line: any) => ({
          ...line,
          id: idSanitizer.generateUUID(),
          invoiceId: sanitizedId,
          itemId: line.itemId ? idSanitizer.getOrCreateUUID(line.itemId) : null,
        }));

        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          invoice_number: invoiceNumber,
          date: inv.date || new Date().toISOString().split('T')[0],
          invoice_date: inv.date || new Date().toISOString().split('T')[0],
          customer_id: customerId,
          customer_name: inv.entityNameAr || (inv as any).customer_name || 'عميل مستورد',
          subtotal,
          tax_amount: taxAmount,
          vat_amount: taxAmount,
          total_amount: totalAmount,
          paid_amount: paidAmount,
          due_amount: dueAmount,
          payment_status: (paidAmount >= totalAmount && totalAmount > 0) ? 'PAID' : (paidAmount > 0 ? 'PARTIAL' : (inv.status || 'POSTED')),
          status: inv.status || 'POSTED',
          raw_data: { ...inv, lines: sanitizedLines },
          updated_at: new Date().toISOString(),
        };
      });

      // 3.6 Payment Vouchers
      const vouchersPayload = vouchers.map((v, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(v.id || `vch-${index}`);
        const entityId = v.entityId ? idSanitizer.getOrCreateUUID(v.entityId) : null;
        const accountId = (v.bankAccountId || (v as any).accountId)
          ? idSanitizer.getOrCreateUUID(v.bankAccountId || (v as any).accountId)
          : null;
        const voucherNumber = v.voucherNumber || (v as any).voucher_number || `VCH-${String(index + 1).padStart(4, '0')}`;

        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          voucher_number: voucherNumber,
          type: v.type || 'RECEIPT',
          date: v.date || new Date().toISOString().split('T')[0],
          amount: Number(v.amount || 0),
          payment_method: v.paymentMethod || 'CASH',
          entity_type: v.entityType || 'CUSTOMER',
          entity_id: entityId,
          entity_name: v.entityNameAr || (v as any).entity_name || '',
          account_id: accountId,
          notes: v.notes || (v as any).description || '',
          status: v.status || 'POSTED',
          updated_at: new Date().toISOString(),
        };
      });

      // 3.7 Journal Entries
      const journalsPayload = journals.map((j, index) => {
        const sanitizedId = idSanitizer.getOrCreateUUID(j.id || `jv-${index}`);
        const entryNumber = j.entryNumber || (j as any).entry_number || `JV-${String(index + 1).padStart(4, '0')}`;
        
        // Remap line account IDs to sanitized account UUIDs
        const sanitizedLines = (j.lines || []).map((line) => {
          const accId = line.accountId ? idSanitizer.getOrCreateUUID(line.accountId) : null;
          return {
            ...line,
            id: line.id ? idSanitizer.getOrCreateUUID(line.id) : idSanitizer.generateUUID(),
            accountId: accId,
          };
        });

        return {
          id: sanitizedId,
          company_id: activeCompanyUUID,
          entry_number: entryNumber,
          date: j.date || new Date().toISOString().split('T')[0],
          description: j.description || (j as any).memo || '',
          status: j.status || 'POSTED',
          reference: j.reference || null,
          reference_id: j.referenceId ? idSanitizer.getOrCreateUUID(j.referenceId) : null,
          total_debit: Number(j.totalDebit || 0),
          total_credit: Number(j.totalCredit || 0),
          lines: sanitizedLines,
          updated_at: new Date().toISOString(),
        };
      });

      // ==============================================================================
      // 4. Sequential Safe Execution in Batches with Try/Catch
      // ==============================================================================

      // 4.1 Accounts (onConflict: id)
      if (accountsPayload.length > 0) {
        updateProgress('ACCOUNTS', `جاري استيراد ${accountsPayload.length} حساب مالي بدفعات آمنة...`, 0);
        const accAccepted = await this.safeBatchedUpsert(
          'chart_of_accounts',
          accountsPayload,
          'id',
          report
        );
        report.stats.accounts = accAccepted;
        updateProgress('ACCOUNTS', `تم استيراد ${accAccepted} حساب مالي بنجاح`, accAccepted);
      }

      // 4.2 Customers (onConflict: id)
      if (customersPayload.length > 0) {
        updateProgress('CUSTOMERS', `جاري استيراد ${customersPayload.length} عميل...`, 0);
        const custAccepted = await this.safeBatchedUpsert(
          'customers',
          customersPayload,
          'id',
          report
        );
        report.stats.customers = custAccepted;
        updateProgress('CUSTOMERS', `تم استيراد ${custAccepted} عميل بنجاح`, custAccepted);
      }

      // 4.3 Suppliers (onConflict: id)
      if (suppliersPayload.length > 0) {
        updateProgress('SUPPLIERS', `جاري استيراد ${suppliersPayload.length} مورد...`, 0);
        const suppAccepted = await this.safeBatchedUpsert(
          'suppliers',
          suppliersPayload,
          'id',
          report
        );
        report.stats.suppliers = suppAccepted;
        updateProgress('SUPPLIERS', `تم استيراد ${suppAccepted} مورد بنجاح`, suppAccepted);
      }

      // 4.4 Inventory Items (onConflict: id)
      if (itemsPayload.length > 0) {
        updateProgress('INVENTORY', `جاري استيراد ${itemsPayload.length} صنف ومخزون...`, 0);
        const itemAccepted = await this.safeBatchedUpsert(
          'items',
          itemsPayload,
          'id',
          report
        );
        report.stats.inventory = itemAccepted;
        updateProgress('INVENTORY', `تم استيراد ${itemAccepted} صنف بنجاح`, itemAccepted);
      }

      // 4.5 Invoices (onConflict: company_id, invoice_number with fallback to id)
      if (invoicesPayload.length > 0) {
        updateProgress('INVOICES', `جاري استيراد ${invoicesPayload.length} فاتورة...`, 0);
        const invAccepted = await this.safeBatchedUpsert(
          'invoices',
          invoicesPayload,
          'company_id, invoice_number',
          report
        );
        report.stats.invoices = invAccepted;
        updateProgress('INVOICES', `تم استيراد ${invAccepted} فاتورة بنجاح`, invAccepted);
      }

      // 4.6 Payment Vouchers (onConflict: company_id, voucher_number with fallback to id)
      if (vouchersPayload.length > 0) {
        updateProgress('VOUCHERS', `جاري استيراد ${vouchersPayload.length} سند قبض وصرف...`, 0);
        const vchAccepted = await this.safeBatchedUpsert(
          'payment_vouchers',
          vouchersPayload,
          'company_id, voucher_number',
          report
        );
        report.stats.vouchers = vchAccepted;
        updateProgress('VOUCHERS', `تم استيراد ${vchAccepted} سند بنجاح`, vouchersPayload.length);
      }

      // 4.7 Journal Entries (onConflict: company_id, entry_number with fallback to id)
      if (journalsPayload.length > 0) {
        updateProgress('JOURNALS', `جاري استيراد ${journalsPayload.length} قيد يومية...`, 0);
        const jrnAccepted = await this.safeBatchedUpsert(
          'journal_entries',
          journalsPayload,
          'company_id, entry_number',
          report
        );
        report.stats.journals = jrnAccepted;
        updateProgress('JOURNALS', `تم استيراد ${jrnAccepted} قيد يومية بنجاح`, jrnAccepted);
      }

      // Auto-recalculate accounting balances in database
      try {
        await supabase.rpc('recalculate_company_ledger_balances', { p_company_id: activeCompanyUUID });
      } catch (e) {
        console.warn('Recalculate balances RPC note:', e);
      }

      // ==============================================================================
      // 5. Direct Local Storage & In-Memory Cache Persistence
      //    Guarantees instant visibility across the UI even offline or before query
      // ==============================================================================
      try {
        if (customers.length > 0) {
          const localCust: Customer[] = customers.map((c, i) => {
            const custName = c.nameAr || (c as any).name || (c as any).name_ar || 'عميل مستورد';
            const cId = customersPayload[i]?.id || idSanitizer.getOrCreateUUID(c.id);
            return {
              ...c,
              id: cId,
              code: (c as any).code || `CUST-${String(i + 1).padStart(4, '0')}`,
              nameAr: custName,
              nameEn: c.nameEn || '',
              phone: c.phone || '',
              address: c.address || '',
              city: (c as any).city || 'الكويت',
              balance: Number((c as any).balance || 0),
              openingBalance: Number((c as any).openingBalance ?? (c as any).balance ?? 0),
              isActive: (c as any).isActive ?? true,
            };
          });
          localDataStore.saveCustomers(localCust);
          cacheService.setCustomers(activeCompanyUUID, localCust);
        }

        if (inventory.length > 0) {
          const localInv: InventoryItem[] = inventory.map((item, i) => {
            const itName = item.nameAr || (item as any).name || (item as any).name_ar || 'صنف مستورد';
            const itCode = item.sku || (item as any).code || `SKU-${String(i + 1).padStart(4, '0')}`;
            const itId = itemsPayload[i]?.id || idSanitizer.getOrCreateUUID(item.id);
            return {
              ...item,
              id: itId,
              sku: itCode,
              nameAr: itName,
              nameEn: item.nameEn || '',
              barcode: item.barcode || '',
              category: item.category || 'عام',
              unit: item.unit || 'حبة',
              purchasePrice: Number(item.purchasePrice || (item as any).costPrice || 0),
              costPrice: Number(item.purchasePrice || (item as any).costPrice || 0),
              salePrice: Number(item.salePrice || 0),
              quantityOnHand: Number(item.quantityOnHand ?? (item as any).current_balance ?? 0),
              minQuantityAlert: Number(item.minQuantityAlert ?? 10),
              isActive: (item as any).isActive ?? true,
            };
          });
          localDataStore.saveInventory(localInv);
          cacheService.setItems(activeCompanyUUID, localInv);
        }

        if (suppliers.length > 0) {
          const localSupp: Supplier[] = suppliers.map((s, i) => {
            const suppName = s.nameAr || (s as any).name || (s as any).name_ar || 'مورد مستورد';
            const sId = suppliersPayload[i]?.id || idSanitizer.getOrCreateUUID(s.id);
            return {
              ...s,
              id: sId,
              code: (s as any).code || `SUPP-${String(i + 1).padStart(4, '0')}`,
              nameAr: suppName,
              nameEn: s.nameEn || '',
              phone: s.phone || '',
              address: s.address || '',
              balance: Number((s as any).balance || 0),
              isActive: (s as any).isActive ?? true,
            };
          });
          localDataStore.saveSuppliers(localSupp);
          cacheService.setSuppliers(activeCompanyUUID, localSupp);
        }

        if (accounts.length > 0) {
          const localAcc: Account[] = accounts.map((acc, i) => {
            const aName = acc.nameAr || (acc as any).name || (acc as any).name_ar || 'حساب مستورد';
            const aId = accountsPayload[i]?.id || idSanitizer.getOrCreateUUID(acc.id);
            return {
              ...acc,
              id: aId,
              code: acc.code || `ACC-${String(i + 1).padStart(4, '0')}`,
              nameAr: aName,
              nameEn: acc.nameEn || '',
              category: acc.category || 'ASSET',
              normalBalance: acc.normalBalance || 'DEBIT',
              level: acc.level || 1,
              type: acc.type || 'DETAIL',
              balance: Number(acc.balance || 0),
              currentBalance: Number(acc.currentBalance ?? acc.balance ?? 0),
              isActive: true,
            };
          });
          localDataStore.saveAccounts(localAcc);
          cacheService.setAccounts(activeCompanyUUID, localAcc);
        }

        if (invoices.length > 0) {
          const localInvs: Invoice[] = invoices.map((inv, i) => ({
            ...inv,
            id: invoicesPayload[i]?.id || idSanitizer.getOrCreateUUID(inv.id),
          }));
          localDataStore.saveInvoices(localInvs);
        }

        if (vouchers.length > 0) {
          const localVchs: PaymentVoucher[] = vouchers.map((v, i) => ({
            ...v,
            id: vouchersPayload[i]?.id || idSanitizer.getOrCreateUUID(v.id),
          }));
          localDataStore.saveVouchers(localVchs);
        }

        if (journals.length > 0) {
          const localJrns: JournalEntry[] = journals.map((j, i) => ({
            ...j,
            id: journalsPayload[i]?.id || idSanitizer.getOrCreateUUID(j.id),
          }));
          localDataStore.saveJournals(localJrns);
        }

        if (rawData.company) {
          localDataStore.saveCompany(rawData.company);
        }

        localDataStore.clearTombstones();
      } catch (storageErr) {
        console.warn('LocalDataStore persistence note:', storageErr);
      }

      report.acceptedTotal =
        report.stats.accounts +
        report.stats.customers +
        report.stats.suppliers +
        report.stats.inventory +
        report.stats.invoices +
        report.stats.vouchers +
        report.stats.journals;

      report.fallbackStats = fallbackStats;
      report.autoProvisionedDetails = autoProvisionedDetails;

      const fallbackSummary: string[] = [];
      if (fallbackStats.customersAutoCreated > 0) fallbackSummary.push(`${fallbackStats.customersAutoCreated} عميل افتراضي`);
      if (fallbackStats.suppliersAutoCreated > 0) fallbackSummary.push(`${fallbackStats.suppliersAutoCreated} مورد افتراضي`);
      if (fallbackStats.itemsAutoCreated > 0) fallbackSummary.push(`${fallbackStats.itemsAutoCreated} صنف افتراضي`);
      if (fallbackStats.accountsAutoCreated > 0) fallbackSummary.push(`${fallbackStats.accountsAutoCreated} حساب قياسي`);
      if (fallbackStats.journalsAutoGenerated > 0) fallbackSummary.push(`${fallbackStats.journalsAutoGenerated} قيد متوازن تم توليده`);
      if (fallbackStats.journalsAutoBalanced > 0) fallbackSummary.push(`${fallbackStats.journalsAutoBalanced} قيد تمت موازنته`);

      report.success = report.acceptedTotal > 0 || totalSteps === 0;
      report.message = `تمت استعادة وحفظ ${report.acceptedTotal} سجل بنجاح في قاعدة البيانات.` +
        (fallbackSummary.length > 0 ? ` (المعالجة الذكية: تم إنشاء وتوليد: ${fallbackSummary.join('، ')})` : '');

      try {
        await safeApiFetch('/api/backup/restore', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(parsed),
        });
      } catch (backendSyncErr) {
        console.warn('Sync to Express server backup/restore notice:', backendSyncErr);
      }
      
      updateProgress('COMPLETE', report.message, 0);
      return report;
    } catch (error: any) {
      console.error('ERPBackupImportService fatal error:', error);
      // [DISASTER RECOVERY & ATOMIC ROLLBACK]
      try {
        if (typeof localStoreSnapshot !== 'undefined') {
          localDataStore.saveAccounts(localStoreSnapshot.accounts);
          localDataStore.saveCustomers(localStoreSnapshot.customers);
          localDataStore.saveSuppliers(localStoreSnapshot.suppliers);
          localDataStore.saveInventory(localStoreSnapshot.inventory);
          localDataStore.saveInvoices(localStoreSnapshot.invoices);
          localDataStore.saveVouchers(localStoreSnapshot.vouchers);
          localDataStore.saveJournals(localStoreSnapshot.journals);
          console.warn('ERPBackupImportService: State rolled back successfully following failure.');
        }
      } catch (rollbackErr) {
        console.error('ERPBackupImportService rollback error:', rollbackErr);
      }
      report.success = false;
      report.message = `فشل استيراد النسخة الاحتياطية. تم التراجع التلقائي وحماية البيانات القائمة: ${error.message || 'خطأ غير معروف'}`;
      report.errors.push(error.message || 'Fatal exception');
      return report;
    }
  }

  /**
   * Helper to perform batched upserts in chunks of 25 with fallback item-level retry
   * to guarantee that a single bad row never fails other valid rows in the batch.
   */
  private static async safeBatchedUpsert(
    tableName: string,
    payloads: any[],
    onConflict: string,
    report: ImportResultReport
  ): Promise<number> {
    const BATCH_SIZE = 25;
    let acceptedCount = 0;

    for (let i = 0; i < payloads.length; i += BATCH_SIZE) {
      const batch = payloads.slice(i, i + BATCH_SIZE);
      try {
        const { error } = await supabase
          .from(tableName)
          .upsert(batch, { onConflict, ignoreDuplicates: false });

        if (error) {
          console.warn(`[Batch Warning] ${tableName} batch error (${error.message}). Retrying items individually...`);
          // Item-level resilient fallback
          for (const item of batch) {
            try {
              let itemRes = await supabase
                .from(tableName)
                .upsert([item], { onConflict, ignoreDuplicates: false });

              // If compound onConflict failed, retry with primary key 'id'
              if (itemRes.error && onConflict !== 'id') {
                itemRes = await supabase
                  .from(tableName)
                  .upsert([item], { onConflict: 'id', ignoreDuplicates: false });
              }

              if (itemRes.error) {
                report.failedTotal++;
                const itemRef = item.code || item.sku || item.invoice_number || item.voucher_number || item.entry_number || item.name || item.id;
                report.errors.push(`[${tableName}] تخطي السجل ${itemRef}: ${itemRes.error.message}`);
              } else {
                acceptedCount++;
              }
            } catch (itemEx: any) {
              report.failedTotal++;
              report.errors.push(`[${tableName}] خطأ في السجل: ${itemEx?.message || 'غير معروف'}`);
            }
          }
        } else {
          acceptedCount += batch.length;
        }
      } catch (batchEx: any) {
        console.warn(`[Batch Exception] in ${tableName}:`, batchEx);
        // Fallback item by item using 'id'
        for (const item of batch) {
          try {
            const { error: fallbackErr } = await supabase
              .from(tableName)
              .upsert([item], { onConflict: 'id', ignoreDuplicates: false });
            if (!fallbackErr) {
              acceptedCount++;
            } else {
              report.failedTotal++;
              report.errors.push(`[${tableName}] استثناء في السجل: ${fallbackErr.message}`);
            }
          } catch {
            report.failedTotal++;
          }
        }
      }
    }

    return acceptedCount;
  }
}

/**
 * Main Frontend JSON Backup Restore Handler (handleJsonImport)
 * Adheres strictly to:
 * 1. Overriding legacy company IDs like "company-kw-01" with active company's authenticated UUID.
 * 2. UUID Sanitization with an in-memory mapping object to preserve foreign key relationships.
 * 3. In-memory deduplication keeping the newest record per invoice_number / voucher_number.
 * 4. Safe batched upserts (batches of 20) with onConflict and try/catch per batch.
 */
export async function handleJsonImport(
  jsonInput: string | any,
  currentCompanyId?: string,
  onProgress?: (progress: ImportProgress) => void
): Promise<ImportResultReport> {
  const companyId =
    currentCompanyId ||
    (typeof window !== 'undefined' ? localStorage.getItem('supabase_company_id') : null) ||
    '20000000-0000-0000-0000-000000000001';
  return ERPBackupImportService.importCompanyJsonData(companyId, jsonInput, onProgress);
}


