/**
 * IFRS Accounting & Financial ERP System Types
 */

export type AccountCategory = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
export type NormalBalance = 'DEBIT' | 'CREDIT';

export interface Account {
  id: string;
  code: string; // e.g. "1110"
  nameAr: string; // e.g. "البنك الرئيسي"
  nameEn: string; // e.g. "Main Bank Account"
  category: AccountCategory;
  parentId: string | null; // Null for top-level accounts
  level: number; // 1 for root (الأصول), 2 for sub (الأصول المتداولة), 3 for detail (البنك)
  normalBalance: NormalBalance;
  isSystem: boolean; // Cannot delete core system accounts
  isActive: boolean;
  type?: 'ROOT' | 'HEADER' | 'DETAIL';
  description?: string;
  balance?: number; // Calculated dynamic balance
}

export type JournalStatus = 'DRAFT' | 'POSTED' | 'CANCELLED' | 'REVERSED';

export interface JournalLine {
  id: string;
  accountId: string;
  accountCode: string;
  accountNameAr: string;
  debit: number;
  credit: number;
  memo: string;
  entityType?: 'CUSTOMER' | 'SUPPLIER' | 'NONE';
  entityId?: string;
  entityNameAr?: string;
}

export interface JournalEntry {
  id: string;
  entryNumber: string; // e.g. "JV-2026-0001"
  date: string; // YYYY-MM-DD
  reference: string; // Invoice # or Document ref
  description: string;
  status: JournalStatus;
  lines: JournalLine[];
  totalDebit: number;
  totalCredit: number;
  createdById?: string;
  createdByName?: string;
  createdAt: string;
  postedAt?: string;
  isAutoGenerated?: boolean;
  sourceModule?: 'MANUAL' | 'SALES_INVOICE' | 'PURCHASE_INVOICE' | 'RECEIPT' | 'PAYMENT' | 'INVENTORY' | 'OPENING';
  sourceId?: string;
}

export interface GeneralLedgerMovement {
  id: string;
  journalEntryId: string;
  entryNumber: string;
  date: string;
  reference: string;
  description: string;
  debit: number;
  credit: number;
  runningBalance: number;
}

export interface GeneralLedgerReport {
  account: Account;
  startDate: string;
  endDate: string;
  openingBalance: number;
  totalDebit: number;
  totalCredit: number;
  closingBalance: number;
  movements: GeneralLedgerMovement[];
}

export interface TrialBalanceItem {
  account: Account;
  openingBalanceDebit: number;
  openingBalanceCredit: number;
  movementDebit: number;
  movementCredit: number;
  endingBalanceDebit: number;
  endingBalanceCredit: number;
}

export interface TrialBalanceReport {
  asOfDate: string;
  items: TrialBalanceItem[];
  totalOpeningDebit: number;
  totalOpeningCredit: number;
  totalMovementDebit: number;
  totalMovementCredit: number;
  totalEndingDebit: number;
  totalEndingCredit: number;
  isBalanced: boolean;
}

// Financial Statements according to IFRS
export interface IncomeStatementItem {
  accountCode: string;
  accountNameAr: string;
  amount: number;
}

export interface IncomeStatementReport {
  startDate: string;
  endDate: string;
  revenues: IncomeStatementItem[];
  totalRevenue: number;
  cogs: IncomeStatementItem[];
  totalCogs: number;
  grossProfit: number;
  expenses: IncomeStatementItem[];
  totalExpenses: number;
  netIncome: number;
}

export interface BalanceSheetSection {
  categoryNameAr: string;
  items: {
    accountCode: string;
    accountNameAr: string;
    amount: number;
  }[];
  totalAmount: number;
}

export interface BalanceSheetReport {
  asOfDate: string;
  currentAssets: BalanceSheetSection;
  nonCurrentAssets: BalanceSheetSection;
  totalAssets: number;
  currentLiabilities: BalanceSheetSection;
  nonCurrentLiabilities: BalanceSheetSection;
  totalLiabilities: number;
  equity: BalanceSheetSection;
  periodNetIncome: number;
  totalEquity: number;
  totalLiabilitiesAndEquity: number;
  isBalanced: boolean;
}

export interface CashFlowReport {
  startDate: string;
  endDate: string;
  operatingCashFlow: {
    netIncome: number;
    adjustments: { label: string; amount: number }[];
    totalOperating: number;
  };
  investingCashFlow: {
    items: { label: string; amount: number }[];
    totalInvesting: number;
  };
  financingCashFlow: {
    items: { label: string; amount: number }[];
    totalFinancing: number;
  };
  netCashChange: number;
  openingCash: number;
  closingCash: number;
}

// Entities & Invoicing
export interface Customer {
  id: string;
  code: string;
  nameAr: string;
  nameEn: string;
  taxNumber?: string;
  phone?: string;
  email?: string;
  address?: string;
  governorate?: string;
  city?: string;
  balance: number;
  currentBalance?: number;
  creditLimit?: number;
  accountId?: string;
  openingBalance?: number;
  openingBalanceDate?: string;
  isActive?: boolean;
}

export interface Supplier {
  id: string;
  code: string;
  nameAr: string;
  nameEn: string;
  taxNumber?: string;
  phone?: string;
  email?: string;
  address?: string;
  governorate?: string;
  city?: string;
  balance: number;
  currentBalance?: number;
  creditLimit?: number;
  accountId?: string;
  openingBalance?: number;
  openingBalanceDate?: string;
  isActive?: boolean;
}

export type UserRole = 'ADMIN' | 'CHIEF_ACCOUNTANT' | 'ACCOUNTANT' | 'SALES' | 'AUDITOR';

export interface SystemUser {
  id: string;
  name: string;
  username: string;
  email: string;
  role: UserRole;
  roleTitleAr: string;
  avatar?: string;
  isActive: boolean;
  pinCode?: string;
  phone?: string;
  createdAt?: string;
}

export interface UnitDefinition {
  id: string;
  code: string;
  nameAr: string;
  nameEn: string;
  conversionFactor: number;
  isBaseUnit: boolean;
  description?: string;
}

export interface InventoryItem {
  id: string;
  sku: string;
  barcode?: string;
  nameAr: string;
  nameEn: string;
  category: string;
  unit: string; // e.g. "حبة", "قطعة", "طقم"
  unitsPerPack: number; // الشد / عدد الحبات في العبوة الكبرى (مثلاً 12 حبة في الكرتون)
  packUnit?: string; // e.g. "كرتون", "شدة", "صندوق"
  purchasePrice: number;
  costPrice?: number;
  salePrice: number;
  quantityOnHand: number;
  initialQuantity?: number;
  quantity?: number;
  minQuantityAlert: number;
  isActive: boolean;
}

export type InvoiceType = 'SALES' | 'PURCHASE' | 'SALES_RETURN' | 'PURCHASE_RETURN';
export type InvoiceStatus = 'DRAFT' | 'POSTED' | 'PAID' | 'PARTIALLY_PAID' | 'CANCELLED';

export interface InvoiceLine {
  id: string;
  itemId: string;
  itemSku: string;
  barcode?: string;
  itemNameAr: string;
  unit: string; // e.g. "حبة" or "كرتون"
  unitsPerPack: number; // الشد (عدد الحبات بالعبوة / الكرتون)
  quantity: number; // إجمالي عدد الوحدات الأساسية
  packQuantity?: number; // عدد الكراتين/الشدات المباعة إن كان البيع بالشد
  unitPrice: number;
  subtotal: number;
  discountType?: 'PERCENT' | 'FIXED';
  discountValue?: number;
  discountAmount?: number;
  vatRate: number; // e.g. 0 for 0%
  vatAmount: number;
  total: number;
  notes?: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string; // e.g. "INV-2026-001"
  type: InvoiceType;
  paymentTerms?: 'CASH' | 'CREDIT'; // نقدي (كاش) أو آجل (ذمم)
  entityId: string; // Customer or Supplier ID
  entityNameAr: string;
  date: string;
  dueDate: string;
  status: InvoiceStatus;
  lines: InvoiceLine[];
  subtotal: number;
  vatTotal: number;
  discountType?: 'PERCENT' | 'FIXED';
  discountValue?: number;
  discountTotal: number;
  grandTotal: number;
  paidAmount: number;
  dueAmount: number;
  salesPerson?: string;
  receiverName?: string;
  journalEntryId?: string;
  notes?: string;
  allowNegativeStock?: boolean;
  negativeStockApprovedBy?: string;
  negativeStockApprovedByName?: string;
  negativeStockReason?: string;
  createdAt: string;
}

export interface NegativeStockAlert {
  id: string;
  invoiceId: string;
  invoiceNumber: string;
  itemId: string;
  itemNameAr: string;
  sku: string;
  availableQtyAtSale: number;
  soldQty: number;
  resultingNegativeQty: number;
  approvedByUid: string;
  approvedByName: string;
  reason: string;
  status: 'PENDING_REPLENISHMENT' | 'RESOLVED';
  createdAt: string;
}

export interface PaymentVoucher {
  id: string;
  voucherNumber: string; // e.g. "PV-2026-001" or "RV-2026-001"
  type: 'RECEIPT' | 'PAYMENT'; // RECEIPT = Receipt from Customer (قبض), PAYMENT = Payment to Supplier (صرف)
  date: string;
  entityType: 'CUSTOMER' | 'SUPPLIER';
  entityId: string;
  entityNameAr: string;
  amount: number;
  paymentMethod: 'BANK' | 'CASH';
  bankAccountId: string; // Account ID for cash/bank
  invoiceId?: string;
  reference: string;
  notes: string;
  status?: 'POSTED' | 'CANCELLED';
  journalEntryId?: string;
  createdAt: string;
}

export interface ProductionLineItem {
  itemId: string;
  itemSku: string;
  itemNameAr: string;
  unit: string;
  quantityRequired: number;
  unitCost: number;
  totalCost: number;
}

export type ProductionOrderStatus = 'DRAFT' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

export interface ProductionOrder {
  id: string;
  orderNumber: string; // e.g. "PRD-2026-001"
  date: string;
  targetItemId: string; // Finished spice / packaged product
  targetItemNameAr: string;
  targetSku: string;
  targetQuantity: number;
  targetUnit: string;
  rawMaterials: ProductionLineItem[];
  overheadCost: number; // تكاليف التشغيل والطحن
  totalProductionCost: number;
  unitProductionCost: number;
  status: ProductionOrderStatus;
  notes?: string;
  millLine?: string; // مثلاً: "خط طحن البهارات رقم 1"
  operatorName?: string;
  journalEntryId?: string;
  createdAt: string;
  completedAt?: string;
}

export interface FinancialKPIs {
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
  totalRevenue: number;
  totalExpenses: number;
  netProfit: number;
  cashAndBankBalance: number;
  accountsReceivableTotal: number;
  accountsPayableTotal: number;
  inventoryTotalValue: number;
  unpaidInvoicesCount: number;
}

export interface CompanyProfile {
  id?: string;
  nameAr: string;
  nameEn: string;
  tradeName?: string;
  activityAr?: string;
  activityEn?: string;
  legalForm: string;
  taxNumber: string;
  crNumber: string;
  commercialRegNumber?: string;
  commercialRegistration?: string;
  currency?: string;
  crIssueDate?: string;
  crExpiryDate?: string;
  chamberNumber?: string;
  vatRate: number;
  vatType: 'NONE' | 'MONTHLY' | 'QUARTERLY';
  zatcaPhase: 'PHASE_1_BASIC' | 'PHASE_2_INTEGRATED';
  zatcaEnv: 'SANDBOX' | 'PRODUCTION';
  
  // Address & Contacts
  buildingNo?: string;
  streetName?: string;
  district?: string;
  city: string;
  country: string;
  postalCode?: string;
  additionalNo?: string;
  phone: string;
  mobile?: string;
  email: string;
  website?: string;
  
  // Financial & Accounting Settings
  fiscalYearStart: string;
  fiscalYearEnd: string;
  functionalCurrency: string;
  accountingBasis: 'ACCRUAL' | 'CASH';
  inventoryCosting: 'WEIGHTED_AVERAGE' | 'FIFO' | 'LIFO';
  depreciationMethod: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
  decimalPlaces: number;
  allowNegativeInventory?: boolean; // السماح بالبيع بالسالب ونفاد المخزون
  allowNegativeBalance?: boolean; // السماح بالحسابات المكشوفة والأرصدة السالبة
  themeColor?: 'blue' | 'navy' | 'classic';
  
  // Signatories
  generalManager: string;
  financialManager: string;
  chiefAccountant: string;
  
  // Branding & Print Config
  logoUrl?: string;
  headerNotes?: string;
  footerNotes?: string;
  showDigitalStamp: boolean;
}
