/**
 * IFRS Accounting & Financial ERP System Types
 */

export type AccountCategory = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
export type NormalBalance = 'DEBIT' | 'CREDIT';

export interface Account {
  id: string;
  code: string; // e.g. "1110"
  nameAr: string; // e.g. "البنك الرئيسي"
  nameEn: string; // e.g. "Main Bank Account"
  category: AccountCategory;
  parentId: string | null; // Null for top-level accounts
  level: number; // 1 for root (الأصول), 2 for sub (الأصول المتداولة), 3 for detail (البنك)
  normalBalance: NormalBalance;
  isSystem: boolean; // Cannot delete core system accounts
  isActive: boolean;
  type?: 'ROOT' | 'HEADER' | 'DETAIL';
  description?: string;
  balance?: number; // Calculated dynamic balance
}

export type JournalStatus = 'DRAFT' | 'POSTED' | 'CANCELLED' | 'REVERSED';

export interface JournalLine {
  id: string;
  accountId: string;
  accountCode: string;
  accountNameAr: string;
  debit: number;
  credit: number;
  memo: string;
  entityType?: 'CUSTOMER' | 'SUPPLIER' | 'NONE';
  entityId?: string;
  entityNameAr?: string;
  companyId?: string;
}

export interface JournalEntry {
  id: string;
  companyId?: string;
  entryNumber: string; // e.g. "JV-2026-0001"
  date: string; // YYYY-MM-DD
  reference: string; // Invoice # or Document ref
  description: string;
  status: JournalStatus;
  lines: JournalLine[];
  totalDebit: number;
  totalCredit: number;
  createdById?: string;
  createdByName?: string;
  createdAt: string;
  postedAt?: string;
  isAutoGenerated?: boolean;
  sourceModule?: 'MANUAL' | 'SALES_INVOICE' | 'PURCHASE_INVOICE' | 'RECEIPT' | 'PAYMENT' | 'INVENTORY' | 'OPENING';
  sourceId?: string;
}

export interface GeneralLedgerMovement {
  id: string;
  journalEntryId: string;
  entryNumber: string;
  date: string;
  reference: string;
  description: string;
  debit: number;
  credit: number;
  runningBalance: number;
}

export interface GeneralLedgerReport {
  account: Account;
  startDate: string;
  endDate: string;
  openingBalance: number;
  totalDebit: number;
  totalCredit: number;
  closingBalance: number;
  movements: GeneralLedgerMovement[];
}

export interface TrialBalanceItem {
  account: Account;
  openingBalanceDebit: number;
  openingBalanceCredit: number;
  movementDebit: number;
  movementCredit: number;
  endingBalanceDebit: number;
  endingBalanceCredit: number;
}

export interface TrialBalanceReport {
  asOfDate: string;
  items: TrialBalanceItem[];
  totalOpeningDebit: number;
  totalOpeningCredit: number;
  totalMovementDebit: number;
  totalMovementCredit: number;
  totalEndingDebit: number;
  totalEndingCredit: number;
  isBalanced: boolean;
}

// Financial Statements according to IFRS
export interface IncomeStatementItem {
  accountCode: string;
  accountNameAr: string;
  amount: number;
}

export interface IncomeStatementReport {
  startDate: string;
  endDate: string;
  revenues: IncomeStatementItem[];
  totalRevenue: number;
  cogs: IncomeStatementItem[];
  totalCogs: number;
  grossProfit: number;
  expenses: IncomeStatementItem[];
  totalExpenses: number;
  netIncome: number;
}

export interface BalanceSheetSection {
  categoryNameAr: string;
  items: {
    accountCode: string;
    accountNameAr: string;
    amount: number;
  }[];
  totalAmount: number;
}

export interface BalanceSheetReport {
  asOfDate: string;
  currentAssets: BalanceSheetSection;
  nonCurrentAssets: BalanceSheetSection;
  totalAssets: number;
  currentLiabilities: BalanceSheetSection;
  nonCurrentLiabilities: BalanceSheetSection;
  totalLiabilities: number;
  equity: BalanceSheetSection;
  periodNetIncome: number;
  totalEquity: number;
  totalLiabilitiesAndEquity: number;
  isBalanced: boolean;
}

export interface CashFlowReport {
  startDate: string;
  endDate: string;
  operatingCashFlow: {
    netIncome: number;
    adjustments: { label: string; amount: number }[];
    totalOperating: number;
  };
  investingCashFlow: {
    items: { label: string; amount: number }[];
    totalInvesting: number;
  };
  financingCashFlow: {
    items: { label: string; amount: number }[];
    totalFinancing: number;
  };
  netCashChange: number;
  openingCash: number;
  closingCash: number;
}

// Entities & Invoicing
export interface CustomerBranch {
  id: string;
  code: string;
  nameAr: string;
  nameEn?: string;
  phone?: string;
  contactPerson?: string;
  address?: string;
  city?: string;
  isDefault?: boolean;
  notes?: string;
}

export interface CustomerPriceListItem {
  itemId: string;
  customPrice: number;
  discountPercentage?: number;
  notes?: string;
}

export interface CustomerPriceList {
  id: string;
  name: string;
  description?: string;
  discountPercentage?: number;
}

export interface Customer {
  id: string;
  code: string;
  nameAr: string;
  nameEn: string;
  taxNumber?: string;
  phone?: string;
  email?: string;
  address?: string;
  governorate?: string;
  city?: string;
  balance: number;
  currentBalance?: number;
  creditLimit?: number;
  accountId?: string;
  openingBalance?: number;
  openingBalanceDate?: string;
  isActive?: boolean;
  branches?: CustomerBranch[];
  priceListId?: string;
  priceListName?: string;
  customPrices?: CustomerPriceListItem[];
  defaultDiscountRate?: number;
}

export interface Supplier {
  id: string;
  code: string;
  nameAr: string;
  nameEn: string;
  taxNumber?: string;
  phone?: string;
  email?: string;
  address?: string;
  governorate?: string;
  city?: string;
  balance: number;
  currentBalance?: number;
  creditLimit?: number;
  accountId?: string;
  openingBalance?: number;
  openingBalanceDate?: string;
  isActive?: boolean;
}

export type UserRole = 'SUPER_ADMIN' | 'ADMIN' | 'EXECUTIVE' | 'GENERAL_MANAGER' | 'CHIEF_ACCOUNTANT' | 'ACCOUNTANT' | 'SALES' | 'AUDITOR' | 'STAFF';

export interface SystemUser {
  id: string;
  name: string;
  username: string;
  email: string;
  role: UserRole;
  roleTitleAr: string;
  avatar?: string;
  isActive: boolean;
  pinCode?: string;
  phone?: string;
  createdAt?: string;
  isPlatformAdmin?: boolean;
}

export interface UnitDefinition {
  id: string;
  code: string;
  nameAr: string;
  nameEn: string;
  conversionFactor: number;
  isBaseUnit: boolean;
  description?: string;
}

export interface InventoryItem {
  id: string;
  sku: string;
  barcode?: string;
  nameAr: string;
  nameEn: string;
  category: string;
  unit: string; // e.g. "حبة", "قطعة", "طقم"
  unitsPerPack: number; // الشد / عدد الحبات في العبوة الكبرى (مثلاً 12 حبة في الكرتون)
  packUnit?: string; // e.g. "كرتون", "شدة", "صندوق"
  description?: string;
  purchasePrice: number;
  costPrice?: number;
  salePrice: number;
  quantityOnHand: number;
  initialQuantity?: number;
  quantity?: number;
  minQuantityAlert: number;
  isActive: boolean;
  companyId?: string;
  company_id?: string;
}

export type InvoiceType = 'SALES' | 'PURCHASE' | 'SALES_RETURN' | 'PURCHASE_RETURN';
export type InvoiceStatus = 'DRAFT' | 'POSTED' | 'PAID' | 'PARTIALLY_PAID' | 'CANCELLED';

export interface InvoiceLine {
  id: string;
  itemId: string;
  itemSku: string;
  barcode?: string;
  itemNameAr: string;
  unit: string; // e.g. "حبة" or "كرتون"
  unitsPerPack: number; // الشد (عدد الحبات بالعبوة / الكرتون)
  quantity: number; // إجمالي عدد الوحدات الأساسية
  packQuantity?: number; // عدد الكراتين/الشدات المباعة إن كان البيع بالشد
  unitPrice: number;
  subtotal: number;
  discountType?: 'PERCENT' | 'FIXED';
  discountValue?: number;
  discountAmount?: number;
  vatRate: number; // e.g. 0 for 0%
  vatAmount: number;
  total: number;
  notes?: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string; // e.g. "INV-2026-001"
  type: InvoiceType;
  paymentTerms?: 'CASH' | 'CREDIT'; // نقدي (كاش) أو آجل (ذمم)
  entityId: string; // Customer or Supplier ID
  entityNameAr: string;
  date: string;
  dueDate: string;
  status: InvoiceStatus;
  lines: InvoiceLine[];
  subtotal: number;
  vatTotal: number;
  discountType?: 'PERCENT' | 'FIXED';
  discountValue?: number;
  discountTotal: number;
  grandTotal: number;
  paidAmount: number;
  dueAmount: number;
  salesPerson?: string;
  salesRepId?: string;
  salesRepName?: string;
  receiverName?: string;
  customerBranchId?: string;
  customerBranchName?: string;
  priceListApplied?: string;
  journalEntryId?: string;
  notes?: string;
  allowNegativeStock?: boolean;
  negativeStockApprovedBy?: string;
  negativeStockApprovedByName?: string;
  negativeStockReason?: string;
  createdAt: string;
}

// Quotations & Proposals
export type QuotationStatus =
  | 'DRAFT'
  | 'SENT'
  | 'ACCEPTED'
  | 'CONVERTED_INVOICE'
  | 'CONVERTED_PRODUCTION'
  | 'REJECTED';

export interface QuotationLine {
  id: string;
  itemId: string;
  itemSku: string;
  itemNameAr: string;
  unit: string;
  unitsPerPack?: number;
  quantity: number;
  unitPrice: number;
  subtotal: number;
  discountType?: 'PERCENT' | 'FIXED';
  discountValue?: number;
  discountAmount?: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  notes?: string;
}

export interface Quotation {
  id: string;
  quotationNumber: string; // e.g. "QUO-2026-001"
  date: string;
  expiryDate: string;
  customerId: string;
  customerNameAr: string;
  salesRepId?: string;
  salesRepName?: string;
  status: QuotationStatus;
  lines: QuotationLine[];
  subtotal: number;
  vatTotal: number;
  discountType?: 'PERCENT' | 'FIXED';
  discountValue?: number;
  discountTotal: number;
  grandTotal: number;
  convertedInvoiceId?: string;
  convertedInvoiceNumber?: string;
  convertedProductionOrderId?: string;
  convertedProductionOrderNumber?: string;
  notes?: string;
  companyId?: string;
  company_id?: string;
  createdAt: string;
}

// Sales Reps Management
export interface SalesRep {
  id: string;
  code: string; // e.g. "REP-01"
  nameAr: string;
  nameEn?: string;
  phone?: string;
  email?: string;
  commissionRate: number; // e.g. 2.5%
  targetAmount?: number;
  isActive: boolean;
  notes?: string;
  companyId?: string;
  company_id?: string;
  createdAt?: string;
}

export interface NegativeStockAlert {
  id: string;
  invoiceId: string;
  invoiceNumber: string;
  itemId: string;
  itemNameAr: string;
  sku: string;
  availableQtyAtSale: number;
  soldQty: number;
  resultingNegativeQty: number;
  approvedByUid: string;
  approvedByName: string;
  reason: string;
  status: 'PENDING_REPLENISHMENT' | 'RESOLVED';
  createdAt: string;
}

export interface PaymentVoucher {
  id: string;
  voucherNumber: string; // e.g. "PV-2026-001" or "RV-2026-001"
  type: 'RECEIPT' | 'PAYMENT'; // RECEIPT = Receipt from Customer (قبض), PAYMENT = Payment to Supplier (صرف)
  date: string;
  entityType: 'CUSTOMER' | 'SUPPLIER';
  entityId: string;
  entityNameAr: string;
  salesRepId?: string;
  salesRepName?: string;
  amount: number;
  paymentMethod: 'BANK' | 'CASH';
  bankAccountId: string; // Account ID for cash/bank
  invoiceId?: string;
  reference: string;
  notes: string;
  status?: 'POSTED' | 'CANCELLED';
  journalEntryId?: string;
  createdAt: string;
}

export type ManufacturingIndustryType =
  | 'FOOD_MILLING'
  | 'ELECTRICAL_LIGHTING'
  | 'CHEMICALS_DETERGENTS'
  | 'PACKAGING_CONVERTING'
  | 'GENERAL_ASSEMBLY';

export interface ManufacturingStandardCategory {
  id: string;
  nameAr: string;
  nameEn?: string;
  type: 'INPUT' | 'OUTPUT' | 'BOTH';
}
export type StandardCategoryDefinition = ManufacturingStandardCategory;

export interface ManufacturingProductionLine {
  id: string;
  nameAr: string;
  nameEn?: string;
  description?: string;
  defaultOperator?: string;
  workstations?: string[];
}
export type StandardLineDefinition = ManufacturingProductionLine;

export interface ManufacturingStandardSettings {
  industryType: ManufacturingIndustryType;
  standardCategories: ManufacturingStandardCategory[];
  standardLines: ManufacturingProductionLine[];
  standardWorkstations: Array<{ id: string; nameAr: string; lineId?: string; throughput?: string }>;
}

export interface ProductionLineItem {
  itemId: string;
  itemSku: string;
  itemNameAr: string;
  unit: string;
  quantityRequired: number;
  unitCost: number;
  totalCost: number;
  role?: 'RAW_MATERIAL' | 'COMPONENT' | 'PACKAGING' | 'AUXILIARY';
  category?: string;
}

export type ProductionOrderStatus =
  | 'DRAFT'
  | 'PLANNED'
  | 'MATERIAL_ISSUED'
  | 'IN_PROGRESS'
  | 'QC_INSPECTION'
  | 'COMPLETED'
  | 'CANCELLED';

export interface QualityInspection {
  inspectorName: string;
  inspectionDate: string;
  purityPercentage: number; // e.g. 99.5%
  moisturePercentage: number; // e.g. 10.2%
  sensoryCheck: 'PASS' | 'FAIL'; // الرائحة واللون والنكهة أو الفحص الظاهري
  foreignMatterCheck: 'PASS' | 'FAIL'; // خلو من العيوب والشوائب
  weightToleranceCheck: 'PASS' | 'FAIL'; // دقة التعبئة أو الأبعاد
  status: 'PASSED' | 'REJECTED' | 'CONDITIONAL';
  coaCertificateNumber?: string; // e.g. "COA-2026-9812"
  notes?: string;
  testedParameters?: Array<{ nameAr: string; standardValue: string; actualValue: string; isPass: boolean }>;
}

export interface EngineeringRoutingStep {
  stepNumber: number;
  nameAr: string;
  workstation: string;
  machineName: string;
  durationMinutes: number;
  specifications: string;
  isCompleted: boolean;
}

export interface ProductionByProduct {
  itemId?: string;
  itemNameAr: string;
  quantity: number;
  unit: string;
  estimatedValue?: number;
}

export interface ProductionOrder {
  id: string;
  orderNumber: string; // e.g. "PRD-2026-001"
  date: string;
  targetItemId: string; // Finished good / packaged product
  targetItemNameAr: string;
  targetSku: string;
  targetQuantity: number;
  targetUnit: string;
  rawMaterials: ProductionLineItem[];
  overheadCost: number; // تكاليف التشغيل والعمالة المباشرة
  totalProductionCost: number;
  unitProductionCost: number;
  status: ProductionOrderStatus;
  notes?: string;
  millLine?: string; // خط الإنتاج (للتوافق القديم)
  productionLineId?: string;
  productionLineNameAr?: string;
  industryType?: ManufacturingIndustryType;
  categoryGroup?: string;
  operatorName?: string;
  journalEntryId?: string;
  createdAt: string;
  completedAt?: string;
  scrapQuantity?: number;
  scrapPercentage?: number;
  scrapReason?: string;
  byProducts?: ProductionByProduct[];
  qualityInspection?: QualityInspection;
  routingSteps?: EngineeringRoutingStep[];
}

export interface CustomerBrandHeader {
  id?: string;
  customerId: string;
  customerNameAr: string;
  customerLogoUrl?: string;
  coBrandLogoUrl?: string;
  headerTitle?: string;
  customHeaderTitle?: string;
  customNotes?: string;
  notes?: string;
}

export interface FinancialKPIs {
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
  totalRevenue: number;
  totalExpenses: number;
  netProfit: number;
  cashAndBankBalance: number;
  accountsReceivableTotal: number;
  accountsPayableTotal: number;
  inventoryTotalValue: number;
  unpaidInvoicesCount: number;
}

export interface DefaultAccountsMapping {
  cashAccountId?: string;          // حساب الصندوق الرئيسي (الخزينة النقدية)
  bankAccountId?: string;          // حساب البنك الرئيسي (الحساب الجاري)
  receivableAccountId?: string;    // حساب العملاء / الذمم المدينة
  payableAccountId?: string;       // حساب الموردين / الذمم الدائنة
  inventoryAccountId?: string;     // حساب المخزون العام للبضائع
  salesAccountId?: string;         // حساب إيرادات المبيعات
  cogsAccountId?: string;          // حساب تكلفة البضاعة المباعة (COGS)
  retainedEarningsAccountId?: string; // حساب الأرباح والخسائر المرحلة / المبقاة
  vatAccountId?: string;           // حساب ضريبة القيمة المضافة / أمانات الضريبة
}

export interface CompanyProfile {
  id?: string;
  nameAr: string;
  nameEn: string;
  tradeName?: string;
  activityAr?: string;
  activityEn?: string;
  legalForm: string;
  taxNumber: string;
  crNumber: string;
  commercialRegNumber?: string;
  commercialRegistration?: string;
  currency?: string;
  crIssueDate?: string;
  crExpiryDate?: string;
  chamberNumber?: string;
  vatRate: number;
  vatType: 'NONE' | 'MONTHLY' | 'QUARTERLY';
  zatcaPhase: 'PHASE_1_BASIC' | 'PHASE_2_INTEGRATED';
  zatcaEnv: 'SANDBOX' | 'PRODUCTION';
  
  // Address & Contacts
  buildingNo?: string;
  streetName?: string;
  district?: string;
  city: string;
  country: string;
  postalCode?: string;
  additionalNo?: string;
  phone: string;
  mobile?: string;
  email: string;
  website?: string;
  
  // Financial & Accounting Settings
  fiscalYearStart: string;
  fiscalYearEnd: string;
  functionalCurrency: string;
  accountingBasis: 'ACCRUAL' | 'CASH';
  inventoryCosting: 'WEIGHTED_AVERAGE' | 'FIFO' | 'LIFO';
  depreciationMethod: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
  decimalPlaces: number;
  allowNegativeInventory?: boolean; // السماح بالبيع بالسالب ونفاد المخزون
  allowNegativeBalance?: boolean; // السماح بالحسابات المكشوفة والأرصدة السالبة
  themeColor?: 'blue' | 'navy' | 'slate' | 'emerald' | 'amber' | 'purple' | 'classic';
  themeMode?: 'light' | 'dark' | 'system';
  
  // Default Accounts Mapping (الربط المحاسبي الافتراضي بدليل الحسابات)
  defaultAccounts?: DefaultAccountsMapping;

  // Signatories
  generalManager: string;
  financialManager: string;
  chiefAccountant: string;
  
  // Branding & Print Config
  logoUrl?: string;
  headerNotes?: string;
  footerNotes?: string;
  showDigitalStamp: boolean;
  customerBrandHeaders?: CustomerBrandHeader[];
}

export type StockMovementType =
  | 'OPENING' // رصيد افتتاحي
  | 'PURCHASE_RECEIPT' // فاتورة مشتريات / توريد مخزني
  | 'SALES_ISSUE' // فاتورة مبيعات / صرف مخزني
  | 'PRODUCTION_IN' // منتج تام الصنع من أمر تشغيل مطحنة
  | 'PRODUCTION_OUT' // مواد أولية مستهلكة في الطحن
  | 'STOCK_ADJUSTMENT' // تسوية جردية (عجز / زيادة)
  | 'INTERNAL_TRANSFER'; // تحويل بين مستودعات

export interface StockMovement {
  id: string;
  date: string;
  time?: string;
  itemId: string;
  itemSku: string;
  itemNameAr: string;
  type: StockMovementType;
  typeTitleAr: string;
  referenceDocNumber: string;
  referenceDocType: string;
  quantityIn: number;
  quantityOut: number;
  balanceAfter: number;
  unit: string;
  unitCost: number;
  totalCostValue: number;
  warehouse?: string;
  notes?: string;
  createdBy?: string;
}

export interface StockAuditSummary {
  totalItemCount: number;
  totalUnitsInStock: number;
  totalValuationAtCost: number;
  totalValuationAtSale: number;
  expectedGrossProfit: number;
  expectedGrossMarginPct: number;
  lowStockCount: number;
  outOfStockCount: number;
  safeStockCount: number;
  excessStockCount: number;
}

export interface TenantCompanyRecord {
  id: string;
  company_name: string;
  owner_email: string;
  password_hash?: string;
  status: 'pending' | 'active' | 'suspended' | 'rejected';
  type?: 'system' | 'demo' | 'client';
  login_code?: string;
  profile_data?: Partial<CompanyProfile>;
  created_at: string;
  updated_at?: string;
}

// ==========================================
// ENTERPRISE EXTENSIONS (جداول وترابطات متقدمة)
// ==========================================

export interface Warehouse {
  id: string;
  code: string;
  nameAr: string;
  nameEn?: string;
  location?: string;
  keeperName?: string;
  phone?: string;
  isDefault?: boolean;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ItemWarehouseStock {
  id: string;
  warehouseId: string;
  itemId: string;
  quantityOnHand: number;
  reservedQuantity?: number;
  minAlertQty?: number;
  maxCapacity?: number;
  shelfLocation?: string;
  lastCountedAt?: string;
}

export interface StockTransferLine {
  id: string;
  itemId: string;
  itemNameAr?: string;
  unit: string;
  quantity: number;
  unitCost: number;
  totalCost: number;
  notes?: string;
}

export interface StockTransfer {
  id: string;
  transferNumber: string;
  transferDate: string;
  fromWarehouseId: string;
  fromWarehouseName?: string;
  toWarehouseId: string;
  toWarehouseName?: string;
  status: 'DRAFT' | 'IN_TRANSIT' | 'COMPLETED' | 'CANCELLED';
  lines: StockTransferLine[];
  totalCostValue: number;
  driverName?: string;
  approvedBy?: string;
  notes?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface CostCenter {
  id: string;
  code: string;
  nameAr: string;
  nameEn?: string;
  parentId?: string;
  level: number;
  category: 'OPERATIONAL' | 'ADMINISTRATIVE' | 'SALES' | 'PROJECT';
  managerName?: string;
  allocatedBudget?: number;
  isActive: boolean;
  createdAt?: string;
}

export interface MasterPriceListItem {
  id: string;
  priceListId: string;
  itemId: string;
  itemNameAr?: string;
  customSalePrice: number;
  minOrderQuantity?: number;
  discountRate?: number;
  notes?: string;
}

export interface MasterPriceList {
  id: string;
  code: string;
  nameAr: string;
  nameEn?: string;
  currency: string;
  isDefault?: boolean;
  defaultDiscountPercent?: number;
  validFrom?: string;
  validTo?: string;
  isActive: boolean;
  items?: MasterPriceListItem[];
  createdAt?: string;
}

export interface FiscalPeriod {
  id: string;
  fiscalYearId: string;
  periodNumber: number;
  nameAr: string;
  startDate: string;
  endDate: string;
  isClosed: boolean;
  closedAt?: string;
}

export interface FiscalYear {
  id: string;
  yearCode: string;
  nameAr: string;
  startDate: string;
  endDate: string;
  isClosed: boolean;
  closedAt?: string;
  closedBy?: string;
  retainedEarningsAccountId?: string;
  periods?: FiscalPeriod[];
  createdAt?: string;
}

export interface SalesOrderLine {
  id: string;
  itemId: string;
  itemNameAr?: string;
  unit: string;
  quantity: number;
  deliveredQuantity: number;
  unitPrice: number;
  discountAmount: number;
  total: number;
  notes?: string;
}

export interface SalesOrder {
  id: string;
  orderNumber: string;
  orderDate: string;
  expectedDeliveryDate?: string;
  customerId: string;
  customerNameAr?: string;
  customerBranchId?: string;
  customerBranchName?: string;
  warehouseId?: string;
  priceListId?: string;
  status: 'PENDING' | 'APPROVED' | 'PARTIALLY_DELIVERED' | 'COMPLETED' | 'CANCELLED';
  lines: SalesOrderLine[];
  subtotal: number;
  discountTotal: number;
  grandTotal: number;
  notes?: string;
  createdAt: string;
}

export interface PurchaseOrderLine {
  id: string;
  itemId: string;
  itemNameAr?: string;
  unit: string;
  quantity: number;
  receivedQuantity: number;
  unitPrice: number;
  total: number;
  notes?: string;
}

export interface PurchaseOrder {
  id: string;
  orderNumber: string;
  orderDate: string;
  expectedDeliveryDate?: string;
  supplierId: string;
  supplierNameAr?: string;
  warehouseId?: string;
  status: 'PENDING' | 'APPROVED' | 'RECEIVED' | 'CANCELLED';
  lines: PurchaseOrderLine[];
  grandTotal: number;
  notes?: string;
  createdAt: string;
}


